# Load library

In [2]:
import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as skl
import anndata as ann
import random, os
from scipy.stats import pearsonr as pr
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score as f1
from sklearn.metrics import precision_recall_curve as prc
from sklearn.metrics import silhouette_score as sil
from sklearn.metrics import auc
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import precision_score, recall_score, average_precision_score
from sklearn.metrics import silhouette_score
from torch_geometric.nn import TransformerConv
from torch_geometric.data import Data
import psutil
import os, sys
import gc
import scipy.sparse as sp
from harmony import harmonize
from tqdm import tqdm
import h5py

In [3]:
sc.set_figure_params(dpi=200)
sc.settings.autoshow = True

# General processing functinos

In [4]:
def whats_memory_eater():
    # Build reverse map of object id -> variable name from globals
    name_map = {id(obj): name for name, obj in globals().items()}

    # Get all tracked objects
    all_objects = gc.get_objects()

    # Safely get size and match variable name
    sizes = []
    for obj in all_objects:
        try:
            size = sys.getsizeof(obj)
            obj_id = id(obj)
            name = name_map.get(obj_id, None)
            sizes.append((size, type(obj), name, repr(obj)[:100]))
        except Exception:
            continue

    # Sort and print top 10
    sizes.sort(reverse=True, key=lambda x: x[0])

    for size, obj_type, name, preview in sizes[:10]:
        print(f"Size: {size / 1024**3} GB | Type: {obj_type} | Name: {name} | Object: {preview}")

In [5]:
def memory_usgae():
    gc.collect()
    process = psutil.Process(os.getpid())
    memory_gb = process.memory_info().rss / 1024**3  # in GB

    print(f"Current memory usage: {memory_gb:.2f} GB")

In [6]:
def pca_and_umap(adata):
    sc.tl.pca(adata, svd_solver="arpack")
    # sc.pl.pca(ad, color='source')
    sc.pp.neighbors(adata)
    sc.tl.umap(adata)

In [7]:
def load_and_preprocess_project(base_path, Project_ID, metadata_idx_key='Cell', 
                                Primary_or_Metastatic = 'Primary', remove_doublets = True, doublet_rate=0.06,
                                further_pre = False, file_prefix= None):
    """
    Load and preprocess a single scRNA-seq project with standard filtering and UMAP.
    
    Assumes the base_path contains:
        - One .mtx file (count matrix)
        - One barcodes.csv
        - One features.csv
        - One meta_all.csv
    """
    # Automatically detect files
    files = os.listdir(base_path)
    metadata_file = None
    
    if file_prefix == None:

        mtx_file = [os.path.join(base_path, f) for f in files if f.endswith('.mtx')][0]
        print(mtx_file)
        barcodes_file = [os.path.join(base_path, f) for f in files if 'barcode' in f][0]
        print(barcodes_file)
        try:
            features_file = [os.path.join(base_path, f) for f in files if 'feature' in f][0]
        except:
            features_file = [os.path.join(base_path, f) for f in files if 'genes' in f][0]
        print(features_file)
        metadata_file = [os.path.join(base_path, f) for f in files if 'meta' in f][0]
        print(metadata_file)
    else:
        for f in files:
            if not f.startswith(file_prefix):
                continue
            if f.endswith('mtx'):
                mtx_file = os.path.join(base_path, f)
                print(mtx_file)
            elif 'barcode' in f:
                barcodes_file = os.path.join(base_path, f)
                print(barcodes_file)
            elif 'feature' in f:
                features_file = os.path.join(base_path, f)
                print(features_file)
            elif 'genes' in f:
                features_file = os.path.join(base_path, f)
                print(features_file)
            elif 'meta' in f:
                metadata_file = os.path.join(base_path, f)
                print(metadata_file)
            else:
                continue
    # print(metadata_file)
    print(f"Loading: {mtx_file}")

    # Load matrix
    adata = sc.read_mtx(mtx_file)
    adata = adata.transpose()  # Important: make cells as rows, genes as columns

    # Load barcodes and features
    if barcodes_file.endswith('tsv'):
        barcodes = pd.read_csv(barcodes_file, sep='\t', header=None)  # no header=None here
    else:
        barcodes = pd.read_csv(barcodes_file)  # no header=None here
    display(barcodes)
    
    if features_file.endswith('tsv'):
        genes = pd.read_csv(features_file, sep='\t', header=None)  # no header=None here
    else:
        genes = pd.read_csv(features_file)  # no header=None here
    display(genes)

    # Assign barcodes and gene names (convert to string)
    if barcodes.shape[1] > 1:
        adata.obs_names = barcodes.iloc[:, 1].astype(str).values
    else:
        adata.obs_names = barcodes.iloc[:, 0].astype(str).values
    
    if genes.shape[1] > 1:
        adata.var_names = genes.iloc[:, 1].astype(str).values
    else:
        adata.var_names = genes.iloc[:, 0].astype(str).values
    # adata.var_names = genes.iloc[:, 0].astype(str).values
    display(adata.to_df())

    # Load and merge metadata
    # if metadata_file
    try:
        if metadata_file.endswith('tsv'):
            metadata = pd.read_csv(metadata_file, sep='\t')
        elif metadata_file.endswith('csv'):
            metadata = pd.read_csv(metadata_file)
        metadata.index = metadata[metadata_idx_key]
        adata.obs = adata.obs.join(metadata, how='left')
    except:
        pass         
    
    # DOUBLET DETECTION (before other filtering)
    if remove_doublets:
        print(f'Running doublet detection on {adata.n_obs} cells...')
                
        sc.external.pp.scrublet(adata, expected_doublet_rate=0.06)
        
        n_cells = adata.n_obs
        n_doublets = adata.obs['predicted_doublet'].sum()
        print(f'  Detected {n_doublets} doublets ({n_doublets/n_cells*100:.1f}%)')
        
        adata = adata[~adata.obs['predicted_doublet']].copy()
        print(f'  After doublet removal: {adata.n_obs} cells')

    # Calculate QC metrics
    adata.var['mt'] = adata.var_names.str.startswith('MT-')
    sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True)

    # Standard cell filtering
    adata = adata[(adata.obs['n_genes_by_counts'] >= 200) & 
                  (adata.obs['n_genes_by_counts'] <= 5000) & 
                  (adata.obs['pct_counts_mt'] <= 20)].copy()
    
    adata.obs['Project_ID'] = Project_ID
    adata.obs['Primary_or_Metastatic'] = Primary_or_Metastatic
    
    # Normalize and log transform
    adata.raw = adata.copy()
    
    if further_pre:
        sc.pp.normalize_total(adata, target_sum=1e4)
        sc.pp.log1p(adata)

        # Highly variable genes
        # sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5)

        # Keep only HVGs
        # adata = adata[:, adata.var.highly_variable]

        # Scale
        sc.pp.scale(adata, max_value=10)

        # PCA
        sc.tl.pca(adata, svd_solver='arpack')

        # Neighbors
        sc.pp.neighbors(adata, n_neighbors=15, n_pcs=40)

        # UMAP
        sc.tl.umap(adata)

    print(f"Finished processing {Project_ID}. Shape: {adata.shape}")

    return adata

In [8]:
def filter_and_recompute(adata, celltype_col, celltypes_to_keep, further_pre = False):
    """
    Filters an AnnData object to keep only specified cell types, 
    then recalculates PCA, neighbors, and UMAP.

    Parameters:
    - adata: AnnData object
    - celltype_col: str, the column in adata.obs containing cell type annotations
    - celltypes_to_keep: list of str, the cell types you want to keep

    Returns:
    - filtered and recalculated AnnData object
    """
    # Step 1: Filter cells
    print(f"Original shape: {adata.shape}")
    adata_filtered = adata[adata.obs[celltype_col].isin(set(celltypes_to_keep))].copy()
    print(f"Filtered shape: {adata_filtered.shape}")

    # Step 2: Recalculate PCA and UMAP
    # (Assumes data is already normalized and scaled)
    if further_pre:
        sc.tl.pca(adata_filtered, svd_solver='arpack')
        sc.pp.neighbors(adata_filtered, n_neighbors=15, n_pcs=40)
        sc.tl.umap(adata_filtered)

    print("Recalculated PCA and UMAP.")
    return adata_filtered

In [9]:
def reprocess_from_raw_layer(adata, Project_ID, Primary_or_Metastatic='Primary', 
                             further_pre=False, remove_doublets=True, doublet_rate=0.06):
    """
    Reprocess a Scanpy AnnData object using its raw layer (e.g., from a published .h5ad).
    This includes doublet removal, normalization, HVG selection, PCA, neighbors, and UMAP.
    
    Parameters:
    - adata: AnnData object, must have .raw set
    - Project_ID: Project identifier
    - Primary_or_Metastatic: Sample type ('Primary' or 'Metastatic')
    - further_pre: Whether to do full preprocessing (normalization, PCA, UMAP)
    - remove_doublets: Whether to run doublet detection and filtering
    - doublet_rate: Expected doublet rate (default 0.06 = 6%)
    
    Returns:
    - Processed AnnData object (modifies in place)
    """
    # Check if raw exists
    if adata.raw is None:
        raise ValueError("AnnData object has no .raw attribute. Cannot proceed with reprocessing.")
    
    # Extract raw counts
    adata.X = adata.raw.X.copy()
    adata.var = adata.raw.var.copy()
    adata.var_names = adata.raw.var_names.copy()
    
    # DOUBLET DETECTION (before other filtering)
    if remove_doublets:
        print(f'Running doublet detection on {adata.n_obs} cells...')
                
        sc.external.pp.scrublet(adata, expected_doublet_rate=0.06)
        
        n_cells = adata.n_obs
        n_doublets = adata.obs['predicted_doublet'].sum()
        print(f'  Detected {n_doublets} doublets ({n_doublets/n_cells*100:.1f}%)')
        
        adata = adata[~adata.obs['predicted_doublet']].copy()
        print(f'  After doublet removal: {adata.n_obs} cells')
    
    # Recalculate mitochondrial content
    adata.var['mt'] = adata.var_names.str.upper().str.startswith('MT-')
    sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True)
    
    print('Standard filtering...')
    # Standard filtering (optional)
    adata = adata[(adata.obs['n_genes_by_counts'] >= 200) &
                  (adata.obs['n_genes_by_counts'] <= 5000) &
                  (adata.obs['pct_counts_mt'] <= 20)].copy()
    
    # Add metadata
    adata.obs['Project_ID'] = Project_ID
    adata.obs['Primary_or_Metastatic'] = Primary_or_Metastatic
    
    if further_pre:
        print('Normalizing...')
        # Normalize and log transform
        sc.pp.normalize_total(adata, target_sum=1e4)
        sc.pp.log1p(adata)
        
        print('Scaling...')
        sc.pp.scale(adata, max_value=10)
        
        print('Computing PCA...')
        sc.tl.pca(adata, svd_solver='arpack')
        
        print('Computing neighbors...')
        sc.pp.neighbors(adata, n_neighbors=15, n_pcs=40)
        
        print('Computing UMAP...')
        sc.tl.umap(adata)
    
    print(f"Reprocessed dataset. Final shape: {adata.shape}")
    return adata

In [10]:
def reprocess_all(adata, further_pre = True):
    """
    Reprocess a Scanpy AnnData object using its raw layer (e.g., from a published .h5ad).
    This includes normalization, HVG selection, PCA, neighbors, and UMAP.

    Parameters:
    - adata: AnnData object, must have .raw set

    Returns:
    - Processed AnnData object (modifies in place)
    """

    # Check if raw exists
    if adata.raw is None:
        raise ValueError("AnnData object has no .raw attribute. Cannot proceed with reprocessing.")

    # Extract raw counts
    adata.X = adata.raw.X.copy()
    adata.var = adata.raw.var.copy()
    adata.var_names = adata.raw.var_names.copy()

    # Recalculate mitochondrial content
    adata.var['mt'] = adata.var_names.str.upper().str.startswith('MT-')
    sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True)
    
    print('Standard filtering...')
    # Standard filtering (optional)
    adata = adata[(adata.obs['n_genes_by_counts'] >= 200) &
                  (adata.obs['n_genes_by_counts'] <= 5000) &
                  (adata.obs['pct_counts_mt'] <= 20)].copy()
    
    # adata.obs['Project_ID'] = Project_ID
    # adata.obs['Primary_or_Metastatic'] = Primary_or_Metastatic
    
    if further_pre:
        # Normalize and log transform
        print('Normalizing...')
        sc.pp.normalize_total(adata, target_sum=1e4)
        sc.pp.log1p(adata)

        # HVG selection
        # sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5)
        # adata = adata[:, adata.var.highly_variable]
        '''
        sc.pp.highly_variable_genes(
            adata,
            flavor="seurat_v3",  # best for batch-aware HVG selection
            n_top_genes=2000,
            batch_key="Final_sample_id"  # or whatever your batch label column is
        )
        '''
        
        # adata = adata[:, adata.var.highly_variable].copy()

        # Scale
        # print('Scaling...')
        # sc.pp.scale(adata, max_value=10)
        print('Computing PCA...')
        # PCA, neighbors, UMAP
        sc.tl.pca(adata, zero_center=False)
        
        print('Computing neighbors...')
        sc.pp.neighbors(adata, n_neighbors=15, n_pcs=40)
        
        print('Computing UMAP...')
        sc.tl.umap(adata)

    print(f"Reprocessed dataset. Final shape: {adata.shape}")
    return adata

In [11]:
def reset_plot():
    # After running scrublet, reset the display settings
    import matplotlib.pyplot as plt
    import matplotlib
    %matplotlib inline

    # Reset matplotlib backend
    matplotlib.use('module://matplotlib_inline.backend_inline')

    # Reset scanpy settings
    import scanpy as sc
    sc.settings.autoshow = True
    sc.settings.set_figure_params(dpi=100, facecolor='white')

# Beast Cacner (BRCA)

## A multi-modal single-cell and spatial expression map of metastatic breast cancer biopsies across clinicopathological features

Paper: https://www.nature.com/articles/s41591-024-03215-z#Fig1

Data downloaded from: https://singlecell.broadinstitute.org/single_cell/study/SCP2702/htapp-mbc

https://cellxgene.cziscience.com/collections/a96133de-e951-4e2d-ace6-59db8b3bfb1d

Link: 
- Matrix: https://datasets.cellxgene.cziscience.com/9dff3651-e629-4519-aaab-dbd21b6b02b1.h5ad
- Patient clinical data: https://static-content.springer.com/esm/art%3A10.1038%2Fs41591-024-03215-z/MediaObjects/41591_2024_3215_MOESM3_ESM.xlsx

In [10]:
ad = sc.read_h5ad('../../Data/BRCA/Multi_modal_breast_cancer/Multi_modal_breast_cancer.scRNAseq.h5ad')
ad

AnnData object with n_obs × n_vars = 157531 × 27361
    obs: 'condition', 'replicate', 'nCount_RNA', 'nFeature_RNA', 'percent.mito', 'RNA_snn_res.0.8', 'seurat_clusters', 'labels_score', 'Order', 'Lane', 'Index', 'cancer', 'reference', 'flowcell', 'min_umis', 'min_genes', 'percent_mito', 'expected_cells', 'total_droplets', 'z_dim', 'z_layers', 'channel_id', 'labels_cl_unif_per_channel', 'filt_median_genes', 'filt_median_umi', 'pass', 'ccpm_id', 'htapp', 'sequenced', 'stage_at_diagnosis', 'metastatic_presentation', 'biopsy_days_after_metastasis', 'ER_primary', 'ER_biopsy', 'PR_primary', 'PR_biopsy', 'HER2_primary', 'HER2_biopsy', 'receptors_primary', 'receptors_biopsy', 'site_biopsy', 'histology_breast', 'histology_biopsy', 'sampleid', 'cnv_cors', 'cnv_cors_max', 'cnv_score', 'cnv_ref_score', 'cnv_score_norm', 'cnv_score_norm_norm', 'cnv_condition', 'cnv_score_norm_norm2', 'pam50_Basal_single', 'pam50_Her2_single', 'pam50_LumA_single', 'pam50_LumB_single', 'pam50_Normal_single', 'pam50_mode_single', 'pam50_subtype_prob_single', 'pam50_Basal_cluster', 'pam50_Her2_cluster', 'pam50_LumA_cluster', 'pam50_LumB_cluster', 'pam50_Normal_cluster', 'pam50_mode_cluster', 'pam50_subtype_prob_cluster', 'S.Score', 'G2M.Score', 'Phase', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'n_counts', 'leiden', 'compartments', 'select_cell', 'author_cell_type', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_ontology_term_id', 'is_primary_data', 'assay_ontology_term_id', 'suspension_type', 'donor_id', 'tissue_type', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'compartments_colors', "dendrogram_['named_cluster_split']", 'hvg', 'leiden', 'neighbors', 'organism', 'organism_ontology_term_id', 'pca', 'rank_genes_groups', 'receptors_biopsy_colors', 'schema_reference', 'schema_version', 'site_biopsy_colors', 'title', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'

In [12]:
# re-process the adata
ad = reprocess_from_raw_layer(ad, 
                              Project_ID='Multi_modal_breast_cancer', 
                              Primary_or_Metastatic='Metastatic',
                              remove_doublets=True,
                              further_pre=False)

Running doublet detection on 157531 cells...

/home/wang3712/.local/lib/python3.8/site-packages/scanpy/preprocessing/_normalization.py:170: UserWarning: Received a view of an AnnData. Making a copy.
  view_to_actual(adata)

Automatically set threshold at doublet score = 0.63
Detected doublet rate = 0.1%
Estimated detectable doublet fraction = 21.6%
Overall doublet rate:
	Expected   = 6.0%
	Estimated  = 0.4%
  Detected 130 doublets (0.1%)
  After doublet removal: 157401 cells
Standard filtering...
Reprocessed dataset. Final shape: (144248, 27361)

In [14]:
# keep only cancer cells
ad = filter_and_recompute(ad, 
                          celltype_col='author_cell_type', 
                          celltypes_to_keep=['MBC', 'MBC_stem-like', 'MBC_chondroid'],
                          further_pre=True)
ad

Original shape: (144248, 27361)
Filtered shape: (79313, 27361)

/home/wang3712/.local/lib/python3.8/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/wang3712/.local/lib/python3.8/site-packages/umap/distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/wang3712/.local/lib/python3.8/site-packages/umap/distances.py:1086: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/wang3712/.local/lib/python3.8/site-packages/umap/umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()

Recalculated PCA and UMAP.

AnnData object with n_obs × n_vars = 79313 × 27361
    obs: 'condition', 'replicate', 'nCount_RNA', 'nFeature_RNA', 'percent.mito', 'RNA_snn_res.0.8', 'seurat_clusters', 'labels_score', 'Order', 'Lane', 'Index', 'cancer', 'reference', 'flowcell', 'min_umis', 'min_genes', 'percent_mito', 'expected_cells', 'total_droplets', 'z_dim', 'z_layers', 'channel_id', 'labels_cl_unif_per_channel', 'filt_median_genes', 'filt_median_umi', 'pass', 'ccpm_id', 'htapp', 'sequenced', 'stage_at_diagnosis', 'metastatic_presentation', 'biopsy_days_after_metastasis', 'ER_primary', 'ER_biopsy', 'PR_primary', 'PR_biopsy', 'HER2_primary', 'HER2_biopsy', 'receptors_primary', 'receptors_biopsy', 'site_biopsy', 'histology_breast', 'histology_biopsy', 'sampleid', 'cnv_cors', 'cnv_cors_max', 'cnv_score', 'cnv_ref_score', 'cnv_score_norm', 'cnv_score_norm_norm', 'cnv_condition', 'cnv_score_norm_norm2', 'pam50_Basal_single', 'pam50_Her2_single', 'pam50_LumA_single', 'pam50_LumB_single', 'pam50_Normal_single', 'pam50_mode_single', 'pam50_subtype_prob_single', 'pam50_Basal_cluster', 'pam50_Her2_cluster', 'pam50_LumA_cluster', 'pam50_LumB_cluster', 'pam50_Normal_cluster', 'pam50_mode_cluster', 'pam50_subtype_prob_cluster', 'S.Score', 'G2M.Score', 'Phase', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'n_counts', 'leiden', 'compartments', 'select_cell', 'author_cell_type', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_ontology_term_id', 'is_primary_data', 'assay_ontology_term_id', 'suspension_type', 'donor_id', 'tissue_type', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'doublet_score', 'predicted_doublet', 'Project_ID', 'Primary_or_Metastatic'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'compartments_colors', "dendrogram_['named_cluster_split']", 'hvg', 'leiden', 'neighbors', 'organism', 'organism_ontology_term_id', 'pca', 'rank_genes_groups', 'receptors_biopsy_colors', 'schema_reference', 'schema_version', 'site_biopsy_colors', 'title', 'umap', 'author_cell_type_colors', 'tissue_colors', 'scrublet', 'sampleid_colors', 'histology_breast_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [ ]:
reset_plot()

sc.pl.umap(ad, color=['sampleid'])
sc.pl.umap(ad, color=['author_cell_type'])
sc.pl.umap(ad, color=['tissue'])
sc.pl.umap(ad, color=['histology_breast'])

In [20]:
ad.obs['Final_cancer_type'] = 'Breast Cancer'
ad.obs['Final_histological_subtype'] = ad.obs.histology_biopsy
ad.obs['Final_molecular_subtype'] = ad.obs.receptors_primary
ad.obs['Final_tissue'] = ad.obs.tissue
ad.obs['Final_sample_id'] = ad.obs.donor_id

In [21]:
patient_clinical_df = pd.read_csv('../../Data/BRCA/Multi_modal_breast_cancer/Patient_clinical.txt', sep='\t')
patient_clinical_df = patient_clinical_df[patient_clinical_df['Profiling method'] == 'scRNAseq']
patient_clinical_df

,ID,HTAN ID,Profiling method,Matching single cell or nucleus data,Mean features per observation,Mean signal per observation,Number of observations,Number of replicates,Biopsy site,Biopsy receptor status,Biopsy receptor status (simplified),Metastatic Presentation,Biopsy days after metastasis,Histology (breast),Treatment status,Treatment most recent class
10,262-602,HTA1_262_602,scRNAseq,scRNAseq,3429.00,9082.89,6804,1,Liver,ER+/PR-/HER2-,HR+/HER2-,Recurrent,0,Invasive ductal carcinoma,on-treatment,Endocrine
12,285-751,HTA1_285_751,scRNAseq,scRNAseq,2162.88,6326.31,6674,1,Liver,ER+/PR-/HER2-,HR+/HER2-,Recurrent,1264,Invasive ductal carcinoma,between treatments,Endocrine
13,309-871,HTA1_309_871,scRNAseq,scRNAseq,966.37,2939.33,2455,1,Bone,ER+/PR-/HER2-,HR+/HER2-,Recurrent,21,Invasive carcinoma with mixed features,on-treatment,Endocrine
14,313-932,HTA1_313_932,scRNAseq,scRNAseq,2346.83,5954.85,12494,1,Liver,ER-/PR-/HER2+,HR-/HER2+,Recurrent,0,Invasive ductal carcinoma with apocrine features,between treatments,HER2-targeted
21,321-1021,HTA1_321_1021,scRNAseq,scRNAseq,1505.50,3975.81,3199,1,Liver,ER+/PR-/HER2-,HR+/HER2-,Recurrent,501,Invasive ductal carcinoma,on-treatment,Endocrine + Chemotherapy
22,330-1082,HTA1_330_1082,scRNAseq,scRNAseq,747.84,1838.29,565,1,Liver,ER+/PR+/HER2-,HR+/HER2-,Recurrent,0,Invasive ductal carcinoma,between treatments,Endocrine
27,364-1321,HTA1_364_1321,scRNAseq,scRNAseq,940.66,2716.94,13167,1,Liver,ER+/PR-/HER2+,HR+/HER2+,Recurrent,103,Invasive ductal carcinoma,between treatments,Endocrine
32,382-1441,HTA1_382_1441,scRNAseq,scRNAseq,1601.67,3467.87,947,1,Bone,ER+/PR+/HER2-,HR+/HER2-,Recurrent,2337,Invasive ductal carcinoma,on-treatment,Endocrine
33,414-1681,HTA1_414_1681,scRNAseq,scRNAseq,824.29,2826.73,877,1,Bone,ER+/PR-/HER2-,HR+/HER2-,Recurrent,69,Invasive carcinoma with mixed features,on-treatment,Endocrine
34,423-1741,HTA1_423_1741,scRNAseq,scRNAseq,1817.19,5273.61,7189,1,Liver,ER+/PR+/HER2-,HR+/HER2-,De novo,1636,Invasive lobular carcinoma,on-treatment,Endocrine
35,425-1771,HTA1_425_1771,scRNAseq,scRNAseq,1987.62,5253.11,2862,1,Breast,ER-/PR-/HER2-,HR-/HER2-,De novo,165,Invasive ductal carcinoma,on-treatment,Chemotherapy
47,562-2581,HTA1_562_2581,scRNAseq,scRNAseq,1082.65,2563.66,811,1,Bone,ER+/PR-/HER2-,HR+/HER2-,Recurrent,9,Invasive ductal carcinoma,off-treatment,distant adjuvant
48,586-8599,HTA1_586_8599,scRNAseq,scRNAseq,1095.10,3254.89,1719,1,Neck,ER-/PR-/HER2-,HR-/HER2-,Recurrent,1797,Invasive ductal carcinoma,between treatments,Immunotherapy
51,611-3062,HTA1_611_3062,scRNAseq,scRNAseq,1867.25,4493.42,10277,1,Liver,ER+/PR+/HER2-,HR+/HER2-,Recurrent,0,Invasive ductal carcinoma,on-treatment,Endocrine
52,627-3242,HTA1_627_3242,scRNAseq,scRNAseq,1121.23,3132.30,5734,1,Liver,ER+/PR-/HER2-,HR+/HER2-,Recurrent,230,Invasive ductal carcinoma,on-treatment,Endocrine
53,649-3422,HTA1_649_3422,scRNAseq,scRNAseq,2182.58,6027.68,6913,1,Neck,ER+/PR-/HER2-,HR+/HER2-,Recurrent,347,Invasive mucinous carcinoma,on-treatment,Chemotherapy
54,662-3602,HTA1_662_3602,scRNAseq,scRNAseq,2629.59,5960.90,9366,1,Liver,ER+/PR+/HER2-,HR+/HER2-,Recurrent,1199,Invasive ductal carcinoma,between treatments,Chemotherapy
55,735-3841,HTA1_735_3841,scRNAseq,scRNAseq,2566.97,7921.76,5119,1,Neck,ER+/PR-/HER2-,HR+/HER2-,Recurrent,1270,Invasive carcinoma with mixed features,on-treatment,Chemotherapy
56,745-3961,HTA1_745_3961,scRNAseq,scRNAseq,1772.37,4355.01,3141,1,Axilla,ER+/PR-/HER2-,HR+/HER2-,Recurrent,8,Invasive ductal carcinoma,on-treatment,Endocrine
58,759-8359,HTA1_759_8359,scRNAseq,scRNAseq,2523.62,6673.24,10423,1,Liver,ER+/PR+/HER2-,HR+/HER2-,Recurrent,1,Ductal carcinoma in situ,between treatments,Endocrine
59,783-4081,HTA1_783_4081,scRNAseq,scRNAseq,2021.50,5547.02,2276,1,Breast,ER+/PR-/HER2-,HR+/HER2-,Recurrent,35,Invasive ductal carcinoma,on-treatment,Endocrine
65,806-6800,HTA1_806_6800,scRNAseq,scRNAseq,769.34,1864.60,423,1,Breast,ER+/PR+/HER2-,HR+/HER2-,De novo,833,Invasive lobular carcinoma,on-treatment,Chemotherapy
66,812-8239,HTA1_812_8239,scRNAseq,scRNAseq,2049.17,5424.83,5463,1,Axilla,ER-/PR-/HER2-,HR-/HER2-,Recurrent,225,Invasive ductal carcinoma,on-treatment,Chemotherapy
73,851-4351,HTA1_851_4351,scRNAseq,scRNAseq,2348.54,5804.99,443,1,Liver,ER+/PR+/HER2-,HR+/HER2-,De novo,1470,Invasive lobular carcinoma,on-treatment,Chemotherapy
74,853-4381,HTA1_853_4381,scRNAseq,scRNAseq,1971.99,6418.12,4742,1,Liver,ER+/PR+/HER2-,HR+/HER2-,De novo,2354,Invasive ductal carcinoma,between treatments,Chemotherapy
104,908-4412,HTA1_908_4412,scRNAseq,scRNAseq,1750.40,4241.96,11087,1,Axilla,ER-/PR-/HER2-,HR-/HER2-,Recurrent,652,Invasive ductal carcinoma,on-treatment,Chemotherapy
105,917-4531,HTA1_917_4531,scRNAseq,scRNAseq,2684.95,7131.53,11074,1,Liver,ER-/PR-/HER2-,HR-/HER2-,Recurrent,13,Invasive ductal carcinoma,off-treatment,distant adjuvant
118,982-7629,HTA1_982_7629,scRNAseq,scRNAseq,3323.53,9332.18,7505,1,Liver,ER+/PR+/HER2-,HR+/HER2-,Recurrent,827,Invasive carcinoma with mixed features,between treatments,Chemotherapy
125,983-7659,HTA1_983_7659,scRNAseq,scRNAseq,2520.19,7277.62,820,1,Liver,ER+/PR+/HER2+,HR+/HER2+,De novo,1466,Invasive ductal carcinoma with mucinous features,between treatments,Chemotherapy
126,988-7749,HTA1_988_7749,scRNAseq,scRNAseq,661.29,2203.48,2962,1,Lung,NaN,NaN,Recurrent,2,Invasive ductal carcinoma,off-treatment,distant adjuvant

In [22]:
# Step 1: Reset index for merging, but save cell IDs
ad.obs['tmp_donor_id'] = [i.replace('SMP-', '').replace('-', '_').replace('HTAPP', 'HTA1') for i in ad.obs['sampleid']]
merged = ad.obs.reset_index().merge(
    patient_clinical_df,
    left_on='tmp_donor_id',
    right_on='HTAN ID',
    how='left'
)

# Step 2: Restore original index (cell barcodes)
merged = merged.set_index('cellid')

# Step 3: Assign back
ad.obs = merged
ad

AnnData object with n_obs × n_vars = 79313 × 27361
    obs: 'condition', 'replicate', 'nCount_RNA', 'nFeature_RNA', 'percent.mito', 'RNA_snn_res.0.8', 'seurat_clusters', 'labels_score', 'Order', 'Lane', 'Index', 'cancer', 'reference', 'flowcell', 'min_umis', 'min_genes', 'percent_mito', 'expected_cells', 'total_droplets', 'z_dim', 'z_layers', 'channel_id', 'labels_cl_unif_per_channel', 'filt_median_genes', 'filt_median_umi', 'pass', 'ccpm_id', 'htapp', 'sequenced', 'stage_at_diagnosis', 'metastatic_presentation', 'biopsy_days_after_metastasis', 'ER_primary', 'ER_biopsy', 'PR_primary', 'PR_biopsy', 'HER2_primary', 'HER2_biopsy', 'receptors_primary', 'receptors_biopsy', 'site_biopsy', 'histology_breast', 'histology_biopsy', 'sampleid', 'cnv_cors', 'cnv_cors_max', 'cnv_score', 'cnv_ref_score', 'cnv_score_norm', 'cnv_score_norm_norm', 'cnv_condition', 'cnv_score_norm_norm2', 'pam50_Basal_single', 'pam50_Her2_single', 'pam50_LumA_single', 'pam50_LumB_single', 'pam50_Normal_single', 'pam50_mode_single', 'pam50_subtype_prob_single', 'pam50_Basal_cluster', 'pam50_Her2_cluster', 'pam50_LumA_cluster', 'pam50_LumB_cluster', 'pam50_Normal_cluster', 'pam50_mode_cluster', 'pam50_subtype_prob_cluster', 'S.Score', 'G2M.Score', 'Phase', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'n_counts', 'leiden', 'compartments', 'select_cell', 'author_cell_type', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_ontology_term_id', 'is_primary_data', 'assay_ontology_term_id', 'suspension_type', 'donor_id', 'tissue_type', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'doublet_score', 'predicted_doublet', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_tissue', 'Final_sample_id', 'tmp_donor_id', 'ID', 'HTAN ID', 'Profiling method', 'Matching single cell or nucleus data', 'Mean features per observation', 'Mean signal per observation', 'Number of observations', 'Number of replicates', 'Biopsy site', 'Biopsy receptor status', 'Biopsy receptor status (simplified)', 'Metastatic Presentation', 'Biopsy days after metastasis', 'Histology (breast)', 'Treatment status', 'Treatment most recent class'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'compartments_colors', "dendrogram_['named_cluster_split']", 'hvg', 'leiden', 'neighbors', 'organism', 'organism_ontology_term_id', 'pca', 'rank_genes_groups', 'receptors_biopsy_colors', 'schema_reference', 'schema_version', 'site_biopsy_colors', 'title', 'umap', 'author_cell_type_colors', 'tissue_colors', 'scrublet', 'sampleid_colors', 'histology_breast_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [23]:
# add more clinical information
ad.obs['Final_patient_age'] = [int(i.split('-')[0]) for i in ad.obs['development_stage']]
ad.obs['Final_patient_stage'] = ad.obs['stage_at_diagnosis']
ad.obs['Final_patient_treatment'] = ad.obs['Treatment most recent class']+' '+ad.obs['Treatment status']

In [24]:
ad.write_h5ad('../../Data/Cancer_cell_data_reprocessed/Multi_modal_breast_cancer.BRCA.h5ad', compression='gzip')

In [25]:
ad

AnnData object with n_obs × n_vars = 79313 × 27361
    obs: 'condition', 'replicate', 'nCount_RNA', 'nFeature_RNA', 'percent.mito', 'RNA_snn_res.0.8', 'seurat_clusters', 'labels_score', 'Order', 'Lane', 'Index', 'cancer', 'reference', 'flowcell', 'min_umis', 'min_genes', 'percent_mito', 'expected_cells', 'total_droplets', 'z_dim', 'z_layers', 'channel_id', 'labels_cl_unif_per_channel', 'filt_median_genes', 'filt_median_umi', 'pass', 'ccpm_id', 'htapp', 'sequenced', 'stage_at_diagnosis', 'metastatic_presentation', 'biopsy_days_after_metastasis', 'ER_primary', 'ER_biopsy', 'PR_primary', 'PR_biopsy', 'HER2_primary', 'HER2_biopsy', 'receptors_primary', 'receptors_biopsy', 'site_biopsy', 'histology_breast', 'histology_biopsy', 'sampleid', 'cnv_cors', 'cnv_cors_max', 'cnv_score', 'cnv_ref_score', 'cnv_score_norm', 'cnv_score_norm_norm', 'cnv_condition', 'cnv_score_norm_norm2', 'pam50_Basal_single', 'pam50_Her2_single', 'pam50_LumA_single', 'pam50_LumB_single', 'pam50_Normal_single', 'pam50_mode_single', 'pam50_subtype_prob_single', 'pam50_Basal_cluster', 'pam50_Her2_cluster', 'pam50_LumA_cluster', 'pam50_LumB_cluster', 'pam50_Normal_cluster', 'pam50_mode_cluster', 'pam50_subtype_prob_cluster', 'S.Score', 'G2M.Score', 'Phase', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'n_counts', 'leiden', 'compartments', 'select_cell', 'author_cell_type', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_ontology_term_id', 'is_primary_data', 'assay_ontology_term_id', 'suspension_type', 'donor_id', 'tissue_type', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'doublet_score', 'predicted_doublet', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_tissue', 'Final_sample_id', 'tmp_donor_id', 'ID', 'HTAN ID', 'Profiling method', 'Matching single cell or nucleus data', 'Mean features per observation', 'Mean signal per observation', 'Number of observations', 'Number of replicates', 'Biopsy site', 'Biopsy receptor status', 'Biopsy receptor status (simplified)', 'Metastatic Presentation', 'Biopsy days after metastasis', 'Histology (breast)', 'Treatment status', 'Treatment most recent class', 'Final_patient_age', 'Final_patient_stage', 'Final_patient_treatment'
    var: 'n_cells', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type'
    uns: 'citation', 'compartments_colors', "dendrogram_['named_cluster_split']", 'hvg', 'leiden', 'neighbors', 'organism', 'organism_ontology_term_id', 'pca', 'rank_genes_groups', 'receptors_biopsy_colors', 'schema_reference', 'schema_version', 'site_biopsy_colors', 'title', 'umap', 'author_cell_type_colors', 'tissue_colors', 'scrublet', 'sampleid_colors', 'histology_breast_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

## A single-cell and spatially resolved atlas of human breast cancers

Paper: https://www.nature.com/articles/s41588-021-00911-1#Fig1

Data downloaded from: https://cellxgene.cziscience.com/collections/65db5560-7aeb-4c66-b150-5bd914480eb8

Link: 
- Matrix: https://datasets.cellxgene.cziscience.com/36ab5d3d-158e-4988-9700-e14fc7102fe4.h5ad
- Patient clinical: https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-021-00911-1/MediaObjects/41588_2021_911_MOESM4_ESM.xlsx

In [26]:
ad = sc.read_h5ad('../../Data/BRCA/Wu_etal_2021_BRCA/Wu_etal_2021_BRCA.h5ad')
ad

AnnData object with n_obs × n_vars = 100064 × 29067
    obs: 'donor_id', 'percent_mito', 'nCount_RNA', 'nFeature_RNA', 'celltype_major', 'celltype_minor', 'celltype_subset', 'subtype', 'gene_module', 'calls', 'normal_cell_call', 'CNA_value', 'batch_run', 'multiplexed', 'cryo_state', 'development_stage_ontology_term_id', 'cancer_type', 'ER', 'PR', 'HER2_IHC', 'HER2_ISH', 'HER2_ISH_ratio', 'Ki67', 'subtype_by_IHC', 'treatment_status', 'treatment_details', 'assay_ontology_term_id', 'organism_ontology_term_id', 'tissue_ontology_term_id', 'suspension_type', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'is_primary_data', 'disease_ontology_term_id', 'grade', 'cell_type_ontology_term_id', 'tissue_type', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length'
    uns: 'citation', 'schema_reference', 'schema_version', 'title'
    obsm: 'X_Three-D', 'X_umap'

In [27]:
# re-process the adata
ad = reprocess_from_raw_layer(ad, 
                              Project_ID='Wu_etal_2021_BRCA', 
                              Primary_or_Metastatic='Primary',
                              further_pre=False)

Running doublet detection on 100064 cells...

/home/wang3712/.local/lib/python3.8/site-packages/scanpy/preprocessing/_normalization.py:170: UserWarning: Received a view of an AnnData. Making a copy.
  view_to_actual(adata)

Automatically set threshold at doublet score = 0.86
Detected doublet rate = 0.0%
Estimated detectable doublet fraction = 0.9%
Overall doublet rate:
	Expected   = 6.0%
	Estimated  = 0.0%
  Detected 0 doublets (0.0%)
  After doublet removal: 100064 cells
Standard filtering...
Reprocessed dataset. Final shape: (96209, 29067)

In [28]:
ad.obs.celltype_major.value_counts()

celltype_major
T-cells              35190
Cancer Epithelial    21839
Myeloid               9386
Endothelial           7361
CAFs                  6374
PVL                   5303
Normal Epithelial     4027
Plasmablasts          3523
B-cells               3206
Name: count, dtype: int64

In [29]:
ad = filter_and_recompute(ad, 
                          celltype_col='celltype_major', 
                          celltypes_to_keep=['Cancer Epithelial'],
                          further_pre=True)
ad

Original shape: (96209, 29067)
Filtered shape: (21839, 29067)
Recalculated PCA and UMAP.

AnnData object with n_obs × n_vars = 21839 × 29067
    obs: 'donor_id', 'percent_mito', 'nCount_RNA', 'nFeature_RNA', 'celltype_major', 'celltype_minor', 'celltype_subset', 'subtype', 'gene_module', 'calls', 'normal_cell_call', 'CNA_value', 'batch_run', 'multiplexed', 'cryo_state', 'development_stage_ontology_term_id', 'cancer_type', 'ER', 'PR', 'HER2_IHC', 'HER2_ISH', 'HER2_ISH_ratio', 'Ki67', 'subtype_by_IHC', 'treatment_status', 'treatment_details', 'assay_ontology_term_id', 'organism_ontology_term_id', 'tissue_ontology_term_id', 'suspension_type', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'is_primary_data', 'disease_ontology_term_id', 'grade', 'cell_type_ontology_term_id', 'tissue_type', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'doublet_score', 'predicted_doublet', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'Project_ID', 'Primary_or_Metastatic'
    var: 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'citation', 'schema_reference', 'schema_version', 'title', 'scrublet', 'pca', 'neighbors', 'umap'
    obsm: 'X_Three-D', 'X_umap', 'X_pca'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [ ]:
sc.pl.umap(ad, color='celltype_minor')
sc.pl.umap(ad, color='disease')
sc.pl.umap(ad, color='donor_id')

In [31]:
patient_clinical_df = pd.read_csv('../../Data/BRCA/Wu_etal_2021_BRCA/Patient_clinical.txt', sep='\t')
patient_clinical_df

,Case ID,Gender,Age,Grade,Cancer Type,ER,PR,HER2 IHC,HER2 ISH (ratio),Ki67,Subtype by IHC,Treatment status,Details of treatment,Notable Pathological features,Stage
0,3586,Female,43,3,IDC,100% 2-3+,100% 2-3+,3+,Amplified (6.8),30-50%,HER2+/ER+,Naïve,-,Multifocal tumour with associatied high grade ...,"pT(m)2, N2a"
1,3838,Female,49,3,IDC,0,0,3+,Amplified (8.91),0.6,HER2+,Naïve,-,Associated high grade DCIS.,"pT2, N1a"
2,3921,Female,60,3,IDC,0,0,3+,Amplified (10.46),>50%,HER2+,Naïve,-,Associated high grade DCIS and focal LVI,"pT2, N2a (Stage IIIA)"
3,3941,Female,50,2,IDC,90% 3+,90% 3+,2+,Non-Amplified,0.1,ER+,Naïve,-,Multifocal tumour with associated high grade DCIS,"pT1c, N1a, Mx"
4,3946,Female,52,3,IDC,0,0,0,Non-Amplified,0.6,TNBC,Naïve,-,Basal phenotype. Reactive lymphoid inflitrate ...,"pT2, N0, Mx"
5,3948,Female,82,3,IDC,90% 2-3+,80% 2+,0,Non-Amplified,~10%,ER+,Naïve,-,"Associated LCIS, with LVI and perineural invasion","pT2, N2a"
6,3963,Female,61,3,IDC,30% 1+,0,0,Non-Amplified,0.43,ER+,Treated,"AC, Paclitaxel, Herceptin (administered for Dx...",Probable recurrence from 3 years prior,"pT2, pN0, Mx, Stage IIA"
7,4040,Female,57,3,IDC,95% 3+,95% 2-3+,0,Non-Amplified,>50%,ER+,Naïve,-,Associated high grade DCIS.,"pT2, N0"
8,4066,Female,41,2,IDC,70% 3+,0,3+,Amplified (7.7),0.3,HER2+/ER+,Treated,Neoadjuvant AC,Associated high grade DCIS and extensive LVI. ...,pT2 N2a Mx
9,4067,Female,85,2,IDC,100% 3+,95% 3+,1+,Non-Amplified,3-4%,ER+,Naïve,-,Associated low grade DCIS and focal perineural...,"pT2, N1(sn), Mx"
10,4290,Female,88,2,IDC,90% 3+,30% 2+,1+,Non-Amplified,0.1,ER+,Naïve,-,"Locally advanced, skin and chest wall muscle i...","pT4b, Nx"
11,4398,Female,52,3,IDC,95% 2+,80% 2+,2+,Non-Amplified,0.75,ER+,Treated,Neoadjuvant FEC-D,Mixed morphology with associated high grade DC...,"pT3, pN2a, pMx, Stage IIIA"
12,4404-1,Female,35,3,IDC,0,0,0,Non-Amplified,0.7,TNBC,Naïve,-,Associated high grade DCIS and focal LVI.,"pT2, N1a, Mx"
13,4461,Female,54,2,IDC,95% 3+,~5% 3+,2+,Non-Amplified,0.15,ER+,Naïve,-,"Associated intermediate to high grade DCIS, LV...","pT3, N1a, Mx"
14,4463,Female,58,2,IDC,100% 2-3+,80% 2-3+,0,Non-Amplified,0.5,ER+,Naïve,-,IDC with areas of lobular -like growth pattern...,"pT3, N1, Mx"
15,4465,Female,54,3,IDC,0,0,0,Non-Amplified,0.7,TNBC,Naïve,-,Basal phenotype - patchy CK5/6 and p63 positiv...,"PT2, N0(sn) Mx"
16,4471,Female,55,2,ILC,100% 3+,100% 3+,0,Non-Amplified,0.2,ER+,Naïve,-,-,"pT3, pN0 (i+)"
17,4495,Female,63,3,IDC,0,0,0,Non-Amplified,0.8,TNBC,Naïve,-,Medullary features,"pT1c, pN0"
18,4497-1,Female,49,3,IDC,0,0,0,Non-Amplified,0.4,TNBC,Naïve,-,Highly atypical cells with circumscribed perip...,"pT2, N1a, Mx"
19,4499-1,Female,47,3,IDC,0,0,0,Non-Amplified,60-70%,TNBC,Naïve,-,BRCA2 mutation,NaN
20,4513,Female,73,3,MBC,0,0,0,Non-Amplified,0.75,TNBC,Treated,"Neoadjuvant AC (4x), Paclitaxel (3x)","Metaplastic, spindle cell carcinoma with areas...","pT3, pN0, Mx, Stage IIB"
21,4515,Female,67,3,IDC,0,0,0,Non-Amplified,0.6,TNBC,Naïve,-,"Basal phenotype: CK5/6+ focal 40%, CK14+ focal...","PpT1c, pN1, Mi, Stage IIA"
22,4517-1,Female,58,3,IDC,0,0,3+,Amplified,0.8,HER2+,Naïve,-,NaN,NaN
23,4523,Female,52,3,MBC,0,0,1+,Non-Amplified,0.9,TNBC,Treated,"Neoadjuvant AC (4x), Paclitaxel (1x)",Metaplastic carcinoma with sebaceous different...,"pT2, pN0 (i+), pM0, Stage IIA"
24,4530,Female,42,2,IDC,95% 2+,95% 3+,1+,Non-Amplified,0.05,ER+,Naïve,-,Multifocal tumour with associated high grade D...,"pT3, pN3, pMx, Stage IIIA"
25,4535,Female,47,2,ILC,95% 3+,70% 2+,2+,Non-Amplified,0.1,ER+,Naïve,-,-,"pT2, pN0 (i+),Stage IIB"

In [34]:
# Step 1: Reset index for merging, but save cell IDs
ad.obs['tmp_donor_id'] = [i.replace('CID', '').replace('A', '').replace('N', '') for i in ad.obs['donor_id']]
patient_clinical_df['Case ID'] = patient_clinical_df['Case ID'].str.replace('-', '')

In [35]:
merged = ad.obs.reset_index().merge(
    patient_clinical_df,
    left_on='tmp_donor_id',
    right_on='Case ID',
    how='left'
)

# Step 2: Restore original index (cell barcodes)
merged = merged.set_index('index')

# Step 3: Assign back
ad.obs = merged
ad

AnnData object with n_obs × n_vars = 21839 × 29067
    obs: 'donor_id', 'percent_mito', 'nCount_RNA', 'nFeature_RNA', 'celltype_major', 'celltype_minor', 'celltype_subset', 'subtype', 'gene_module', 'calls', 'normal_cell_call', 'CNA_value', 'batch_run', 'multiplexed', 'cryo_state', 'development_stage_ontology_term_id', 'cancer_type', 'ER_x', 'PR_x', 'HER2_IHC', 'HER2_ISH', 'HER2_ISH_ratio', 'Ki67_x', 'subtype_by_IHC', 'treatment_status', 'treatment_details', 'assay_ontology_term_id', 'organism_ontology_term_id', 'tissue_ontology_term_id', 'suspension_type', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'is_primary_data', 'disease_ontology_term_id', 'grade', 'cell_type_ontology_term_id', 'tissue_type', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'doublet_score', 'predicted_doublet', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'Project_ID', 'Primary_or_Metastatic', 'tmp_donor_id', 'Case ID', 'Gender', 'Age', 'Grade', 'Cancer Type', 'ER_y', 'PR_y', 'HER2 IHC', 'HER2 ISH (ratio)', 'Ki67_y', 'Subtype by IHC', 'Treatment status', 'Details of treatment', 'Notable Pathological features', 'Stage'
    var: 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'citation', 'schema_reference', 'schema_version', 'title', 'scrublet', 'pca', 'neighbors', 'umap', 'celltype_minor_colors', 'disease_colors', 'donor_id_colors'
    obsm: 'X_Three-D', 'X_umap', 'X_pca'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [36]:
ad.obs['Final_cancer_type'] = 'Breast Cancer'
ad.obs['Final_histological_subtype'] = ad.obs.disease
ad.obs['Final_molecular_subtype'] = ad.obs['subtype_by_IHC']
ad.obs['Final_tissue'] = 'Breast'
ad.obs['Final_sample_id'] = ad.obs.donor_id

In [37]:
ad.obs['Cancer Type'].value_counts()

Cancer Type
IDC    18034
ILC     2120
MBC     1685
Name: count, dtype: int64

In [38]:
ad.obs['Primary_or_Metastatic'] = ad.obs['Primary_or_Metastatic']

In [39]:
# add more clinical information
ad.obs['Final_patient_age'] = ad.obs['Age'].astype(int)
ad.obs['Final_patient_stage'] = ad.obs['Stage']
ad.obs['Final_patient_treatment'] = ad.obs['treatment_status'].astype(str) +' '+ad.obs['treatment_details'].astype(str)

In [40]:
ad.raw.shape

(21839, 29067)

In [41]:
ad.write_h5ad('../../Data/Cancer_cell_data_reprocessed/Wu_etal_2021_BRCA.BRCA.h5ad', compression='gzip')

## A pan-cancer blueprint of the heterogeneous tumor microenvironment revealed by single-cell profiling

Paper: https://www.nature.com/articles/s41422-020-0355-0#Fig3

Data downloaded from: https://lambrechtslab.sites.vib.be/en/pan-cancer-blueprint-tumour-microenvironment-0

Link: 
- Matrix: https://lambrechtslab.sites.vib.be/en/pan-cancer-blueprint-tumour-microenvironment-0(Breast cancer - Counts Matrix)
- Patient metadata: https://static-content.springer.com/esm/art%3A10.1038%2Fs41422-020-0355-0/MediaObjects/41422_2020_355_MOESM13_ESM.pdf
- Sequecing quality: https://www.nature.com/
https://static-content.springer.com/esm/art%3A10.1038%2Fs41422-020-0355-0/MediaObjects/41422_2020_355_MOESM14_ESM.pdf

In [44]:
# Set the project directory
project_dir = "../../Data/BRCA/2102-Breastcancer/export/BC_counts/"  # <- change this for each project

# Load and preprocess
ad = load_and_preprocess_project(project_dir, 
                                 Project_ID='2102-Breastcancer', 
                                 Primary_or_Metastatic='Primary',
                                 further_pre=True)

../../Data/BRCA/2102-Breastcancer/export/BC_counts/matrix.mtx
../../Data/BRCA/2102-Breastcancer/export/BC_counts/barcodes.tsv
../../Data/BRCA/2102-Breastcancer/export/BC_counts/genes.tsv
../../Data/BRCA/2102-Breastcancer/export/BC_counts/2103-Breastcancer_metadata.csv
Loading: ../../Data/BRCA/2102-Breastcancer/export/BC_counts/matrix.mtx

                                 0
0      sc5rJUQ024_AAACCTGCAACAACCT
1      sc5rJUQ024_AAACCTGCAAGAAGAG
2      sc5rJUQ024_AAACCTGGTCTCCACT
3      sc5rJUQ024_AAACCTGTCAACGAAA
4      sc5rJUQ024_AAACGGGAGAGTAAGG
...                            ...
44019  sc5rJUQ064_TTTGTCAAGCACCGCT
44020  sc5rJUQ064_TTTGTCAAGCCAGAAC
44021  sc5rJUQ064_TTTGTCAAGGACGAAA
44022  sc5rJUQ064_TTTGTCAGTCTTGTCC
44023  sc5rJUQ064_TTTGTCATCCGGGTGT

[44024 rows x 1 columns]

                  0             1
0      RP11-34P13.3  RP11-34P13.3
1           FAM138A       FAM138A
2             OR4F5         OR4F5
3      RP11-34P13.7  RP11-34P13.7
4      RP11-34P13.8  RP11-34P13.8
...             ...           ...
33689    AC233755.2    AC233755.2
33690    AC233755.1    AC233755.1
33691    AC240274.1    AC240274.1
33692    AC213203.1    AC213203.1
33693       FAM231B       FAM231B

[33694 rows x 2 columns]

,RP11-34P13.3,FAM138A,OR4F5,RP11-34P13.7,RP11-34P13.8,RP11-34P13.14,RP11-34P13.9,FO538757.3,FO538757.2,AP006222.2,...,AC007325.2,BX072566.1,AL354822.1,AC023491.2,AC004556.1,AC233755.2,AC233755.1,AC240274.1,AC213203.1,FAM231B
sc5rJUQ024_AAACCTGCAACAACCT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sc5rJUQ024_AAACCTGCAAGAAGAG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sc5rJUQ024_AAACCTGGTCTCCACT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sc5rJUQ024_AAACCTGTCAACGAAA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sc5rJUQ024_AAACGGGAGAGTAAGG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sc5rJUQ064_TTTGTCAAGCACCGCT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sc5rJUQ064_TTTGTCAAGCCAGAAC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sc5rJUQ064_TTTGTCAAGGACGAAA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sc5rJUQ064_TTTGTCAGTCTTGTCC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sc5rJUQ064_TTTGTCATCCGGGTGT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Running doublet detection on 44024 cells...

/home/wang3712/.local/lib/python3.8/site-packages/scanpy/preprocessing/_normalization.py:170: UserWarning: Received a view of an AnnData. Making a copy.
  view_to_actual(adata)

Automatically set threshold at doublet score = 0.81
Detected doublet rate = 0.0%
Estimated detectable doublet fraction = 0.1%
Overall doublet rate:
	Expected   = 6.0%
	Estimated  = 0.0%
  Detected 0 doublets (0.0%)
  After doublet removal: 44024 cells
Finished processing 2102-Breastcancer. Shape: (40617, 33694)

In [46]:
ad.obs['PatientNumber'] = ad.obs['PatientNumber'].astype(str)

In [ ]:
reset_plot()
sc.pl.umap(ad, color=['CellType'])
sc.pl.umap(ad, color=['PatientNumber'])
# sc.pl.umap(ad, color=['CellFromTumor'])
# sc.pl.umap(ad, color=['TumorSite'])
# sc.pl.umap(ad, color=['Project'])

In [48]:
ad = filter_and_recompute(adata=ad, 
                          celltype_col='CellType', 
                          celltypes_to_keep=['Cancer'],
                          further_pre=True)
ad

Original shape: (40617, 33694)
Filtered shape: (14058, 33694)
Recalculated PCA and UMAP.

AnnData object with n_obs × n_vars = 14058 × 33694
    obs: 'Cell', 'nGene', 'nUMI', 'CellFromTumor', 'PatientNumber', 'TumorType', 'TumorSite', 'CellType', 'doublet_score', 'predicted_doublet', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'Project_ID', 'Primary_or_Metastatic'
    var: 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'mean', 'std'
    uns: 'scrublet', 'log1p', 'pca', 'neighbors', 'umap', 'CellType_colors', 'PatientNumber_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [ ]:
reset_plot()
sc.pl.umap(ad, color=['TumorType', 'PatientNumber'])

In [51]:
patient_cell_number = pd.read_csv("../../Data/BRCA/2102-Breastcancer/2103-Breastcancer_metadata.csv")['PatientNumber'].value_counts()
patient_cell_number = patient_cell_number.to_dict()
patient_cell_number

{42: 4876,
 51: 4862,
 49: 4616,
 45: 4472,
 43: 4251,
 54: 4216,
 41: 3921,
 53: 3641,
 44: 3558,
 48: 2427,
 47: 1719,
 50: 902,
 52: 362,
 46: 201}

In [52]:
patient_seuqncing_meta_df = pd.read_csv('../../Data/BRCA/2102-Breastcancer/Sequencing_quality_S2.txt', sep='\t')
patient_seuqncing_meta_df = patient_seuqncing_meta_df[patient_seuqncing_meta_df['Cancer type'] == 'BC']
patient_seuqncing_meta_df

,Patient number,Cancer type,10X version,Cells,Sample type,Tumour site,UMIs,Saturation (%),Reads
67,BC_1,BC,5' V2,3921,Tumour,Biopsy,23817225,83.4,331894515
68,BC_2,BC,5' V2,4876,Tumour,Biopsy,16583928,65.8,162530552
69,BC_3,BC,5' V2,4251,Tumour,Biopsy,20633409,85.6,309676287
70,BC_4,BC,5' V2,3558,Tumour,Biopsy,13810634,72.7,154003539
71,BC_5,BC,5' V2,4472,Tumour,Biopsy,22094301,65.8,150279221
72,BC_6,BC,5' V2,201,Tumour,Biopsy,1310634,83.0,39183120
73,BC_7,BC,5' V2,1719,Tumour,Biopsy,15089867,71.4,146585647
74,BC_8,BC,5' V2,2427,Tumour,Biopsy,9087189,69.3,151070133
75,BC_9,BC,5' V2,4616,Tumour,Biopsy,28428991,66.8,265636248
76,BC_10,BC,5' V2,902,Tumour,Biopsy,4088085,76.3,39349726
77,BC_11,BC,5' V2,4862,Tumour,Biopsy,28400652,65.9,275631788
78,BC_12,BC,5' V2,362,Tumour,Biopsy,1725747,81.3,24816828
79,BC_12,BC,3' V2,64,Tumour,Biopsy,323793,93.5,15193301
80,BC_12,BC,3' V2,1372,Tumour,Biopsy,8866716,77.5,118432604
81,BC_13,BC,5' V2,3641,Tumour,Biopsy,19494370,70.3,219414682
82,BC_14,BC,5' V2,4216,Tumour,Biopsy,34749191,65.8,284244840
83,BC_15,BC,3' V2,4143,Tumour,Biopsy,20268164,56.9,295259214
84,BC_15,BC,3' V2,347,Tumour,Biopsy,2851324,55.9,157883076
85,BC_16,BC,3' V2,269,Tumour,Biopsy,1070916,67.4,195421321

In [53]:
cells_to_bc_label = dict(zip(patient_seuqncing_meta_df['Cells'], patient_seuqncing_meta_df['Patient number']))
cells_to_bc_label

{3921: 'BC_1',
 4876: 'BC_2',
 4251: 'BC_3',
 3558: 'BC_4',
 4472: 'BC_5',
 201: 'BC_6',
 1719: 'BC_7',
 2427: 'BC_8',
 4616: 'BC_9',
 902: 'BC_10',
 4862: 'BC_11',
 362: 'BC_12',
 64: 'BC_12',
 1372: 'BC_12',
 3641: 'BC_13',
 4216: 'BC_14',
 4143: 'BC_15',
 347: 'BC_15',
 269: 'BC_16'}

In [54]:
patient_number_to_BC_id = dict()
for patient_number in patient_cell_number.keys():
    patient_number_to_BC_id[str(patient_number)] = cells_to_bc_label[patient_cell_number[patient_number]]
patient_number_to_BC_id

{'42': 'BC_2',
 '51': 'BC_11',
 '49': 'BC_9',
 '45': 'BC_5',
 '43': 'BC_3',
 '54': 'BC_14',
 '41': 'BC_1',
 '53': 'BC_13',
 '44': 'BC_4',
 '48': 'BC_8',
 '47': 'BC_7',
 '50': 'BC_10',
 '52': 'BC_12',
 '46': 'BC_6'}

In [55]:
ad.obs['BC_PatientID'] = ad.obs['PatientNumber'].map(patient_number_to_BC_id)
ad.obs

,Cell,nGene,nUMI,CellFromTumor,PatientNumber,TumorType,TumorSite,CellType,doublet_score,predicted_doublet,n_genes_by_counts,total_counts,total_counts_mt,pct_counts_mt,Project_ID,Primary_or_Metastatic,BC_PatientID
sc5rJUQ024_AAACCTGGTCTCCACT,sc5rJUQ024_AAACCTGGTCTCCACT,585,1141,True,41,BC,Biopsy,Cancer,0.049156,False,585,1141.0,12.0,1.051709,2102-Breastcancer,Primary,BC_1
sc5rJUQ024_AAACGGGTCTCGTATT,sc5rJUQ024_AAACGGGTCTCGTATT,312,412,True,41,BC,Biopsy,Cancer,0.075580,False,312,412.0,18.0,4.368932,2102-Breastcancer,Primary,BC_1
sc5rJUQ024_AAAGCAAAGTGCGTGA,sc5rJUQ024_AAAGCAAAGTGCGTGA,366,769,True,41,BC,Biopsy,Cancer,0.065663,False,366,769.0,8.0,1.040312,2102-Breastcancer,Primary,BC_1
sc5rJUQ024_AACGTTGGTTCAGCGC,sc5rJUQ024_AACGTTGGTTCAGCGC,306,479,True,41,BC,Biopsy,Cancer,0.097961,False,306,479.0,3.0,0.626305,2102-Breastcancer,Primary,BC_1
sc5rJUQ024_AACTCAGAGCCAGGAT,sc5rJUQ024_AACTCAGAGCCAGGAT,260,483,True,41,BC,Biopsy,Cancer,0.076683,False,260,483.0,2.0,0.414079,2102-Breastcancer,Primary,BC_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sc5rJUQ064_TTTGTCAAGCACCGCT,sc5rJUQ064_TTTGTCAAGCACCGCT,287,454,True,54,BC,Biopsy,Cancer,0.101216,False,287,454.0,32.0,7.048458,2102-Breastcancer,Primary,BC_14
sc5rJUQ064_TTTGTCAAGCCAGAAC,sc5rJUQ064_TTTGTCAAGCCAGAAC,3037,11414,True,54,BC,Biopsy,Cancer,0.045571,False,3037,11414.0,753.0,6.597161,2102-Breastcancer,Primary,BC_14
sc5rJUQ064_TTTGTCAAGGACGAAA,sc5rJUQ064_TTTGTCAAGGACGAAA,1858,4750,True,54,BC,Biopsy,Cancer,0.031888,False,1858,4750.0,498.0,10.484210,2102-Breastcancer,Primary,BC_14
sc5rJUQ064_TTTGTCAGTCTTGTCC,sc5rJUQ064_TTTGTCAGTCTTGTCC,2537,10251,True,54,BC,Biopsy,Cancer,0.151720,False,2537,10251.0,1558.0,15.198517,2102-Breastcancer,Primary,BC_14
sc5rJUQ064_TTTGTCATCCGGGTGT,sc5rJUQ064_TTTGTCATCCGGGTGT,1130,2163,True,54,BC,Biopsy,Cancer,0.037382,False,1130,2163.0,174.0,8.044383,2102-Breastcancer,Primary,BC_14

In [56]:
patient_meta_df = pd.read_csv('../../Data/BRCA/2102-Breastcancer/Patient_metadata_S1.txt', sep='\t')
patient_meta_df = patient_meta_df[patient_meta_df['Tumor_type'] == 'BC']
# meta_subset = patient_meta_df[['Patient_number', 'Pathological_subtype', 'Molecular_status']]
patient_meta_df

,Patient_number,Tumor_type,Gender,Age_range,Stage,TNM,Pathological_subtype,Molecular_status
20,BC_1,BC,Female,40-45,III,pT1cN0M0,Invasive ductal carcinoma,HER2 positive
21,BC_2,BC,Female,50-55,III,pT2N0M0,Invasive ductal carcinoma,Triple negative
22,BC_3,BC,Female,50-55,III,pT3N0M0,Invasive ductal carcinoma,Triple negative
23,BC_4,BC,Female,86-90,III,pT1N0M0,Invasive ductal carcinoma,Triple negative
24,BC_5,BC,Female,60-65,III,pT2N1aM0,Invasive apocrine carcinoma,Triple negative
25,BC_6,BC,Female,70-75,III,pT2N0M0,Invasive ductal carcinoma,HER2 positive
26,BC_7,BC,Female,80-85,III,pT3N0M0,Metaplastic carcinoma,Triple negative
27,BC_8,BC,Female,60-65,III,pT3N0M0,Invasive ductal carcinoma,HER2 positive
28,BC_9,BC,Female,40-45,III,pT2N1M0,Invasive ductal carcinoma,Luminal-HER2+
29,BC_10,BC,Female,50-55,III,pT2N0M0,Invasive ductal carcinoma,Triple negative
30,BC_11,BC,Female,46-50,III,pT1cN0M0,Invasive ductal carcinoma,Triple negative
31,BC_12,BC,Female,76-80,III,pT2NxM0,Invasive ductal carcinoma,Triple negative
32,BC_13,BC,Female,60-65,III,pT2N1M0,Invasive ductal carcinoma,Luminal B-like
33,BC_14,BC,Female,46-50,II,pT2N1M0,Invasive ductal carcinoma,Luminal A-like
34,BC_15,BC,Female,66-70,III,pT1N0M0,Invasive ductal carcinoma,Triple negative
35,BC_16,BC,Female,60-65,III,pT2N1M0,Invasive ductal carcinoma,Luminal B ‚Äìlike

In [57]:
ad.obs = ad.obs.merge(patient_meta_df, left_on='BC_PatientID', right_on='Patient_number', how='left')
ad.obs

,Cell,nGene,nUMI,CellFromTumor,PatientNumber,TumorType,TumorSite,CellType,doublet_score,predicted_doublet,...,Primary_or_Metastatic,BC_PatientID,Patient_number,Tumor_type,Gender,Age_range,Stage,TNM,Pathological_subtype,Molecular_status
0,sc5rJUQ024_AAACCTGGTCTCCACT,585,1141,True,41,BC,Biopsy,Cancer,0.049156,False,...,Primary,BC_1,BC_1,BC,Female,40-45,III,pT1cN0M0,Invasive ductal carcinoma,HER2 positive
1,sc5rJUQ024_AAACGGGTCTCGTATT,312,412,True,41,BC,Biopsy,Cancer,0.075580,False,...,Primary,BC_1,BC_1,BC,Female,40-45,III,pT1cN0M0,Invasive ductal carcinoma,HER2 positive
2,sc5rJUQ024_AAAGCAAAGTGCGTGA,366,769,True,41,BC,Biopsy,Cancer,0.065663,False,...,Primary,BC_1,BC_1,BC,Female,40-45,III,pT1cN0M0,Invasive ductal carcinoma,HER2 positive
3,sc5rJUQ024_AACGTTGGTTCAGCGC,306,479,True,41,BC,Biopsy,Cancer,0.097961,False,...,Primary,BC_1,BC_1,BC,Female,40-45,III,pT1cN0M0,Invasive ductal carcinoma,HER2 positive
4,sc5rJUQ024_AACTCAGAGCCAGGAT,260,483,True,41,BC,Biopsy,Cancer,0.076683,False,...,Primary,BC_1,BC_1,BC,Female,40-45,III,pT1cN0M0,Invasive ductal carcinoma,HER2 positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14053,sc5rJUQ064_TTTGTCAAGCACCGCT,287,454,True,54,BC,Biopsy,Cancer,0.101216,False,...,Primary,BC_14,BC_14,BC,Female,46-50,II,pT2N1M0,Invasive ductal carcinoma,Luminal A-like
14054,sc5rJUQ064_TTTGTCAAGCCAGAAC,3037,11414,True,54,BC,Biopsy,Cancer,0.045571,False,...,Primary,BC_14,BC_14,BC,Female,46-50,II,pT2N1M0,Invasive ductal carcinoma,Luminal A-like
14055,sc5rJUQ064_TTTGTCAAGGACGAAA,1858,4750,True,54,BC,Biopsy,Cancer,0.031888,False,...,Primary,BC_14,BC_14,BC,Female,46-50,II,pT2N1M0,Invasive ductal carcinoma,Luminal A-like
14056,sc5rJUQ064_TTTGTCAGTCTTGTCC,2537,10251,True,54,BC,Biopsy,Cancer,0.151720,False,...,Primary,BC_14,BC_14,BC,Female,46-50,II,pT2N1M0,Invasive ductal carcinoma,Luminal A-like
14057,sc5rJUQ064_TTTGTCATCCGGGTGT,1130,2163,True,54,BC,Biopsy,Cancer,0.037382,False,...,Primary,BC_14,BC_14,BC,Female,46-50,II,pT2N1M0,Invasive ductal carcinoma,Luminal A-like

In [58]:
ad.obs['Final_cancer_type'] = 'Breast Cancer'
ad.obs['Final_histological_subtype'] = ad.obs.Pathological_subtype
ad.obs['Final_molecular_subtype'] = ad.obs['Molecular_status']
ad.obs['Final_tissue'] = 'Breast'
ad.obs['Final_sample_id'] = ad.obs['BC_PatientID']

In [59]:
# add more clinical information
ad.obs['Final_patient_age'] = ad.obs['Age_range']
ad.obs['Final_patient_stage'] = ad.obs['TNM']
ad.obs['Final_patient_treatment'] = 'Naïve'

In [61]:
ad

AnnData object with n_obs × n_vars = 14058 × 33694
    obs: 'Cell', 'nGene', 'nUMI', 'CellFromTumor', 'PatientNumber', 'TumorType', 'TumorSite', 'CellType', 'doublet_score', 'predicted_doublet', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'Project_ID', 'Primary_or_Metastatic', 'BC_PatientID', 'Patient_number', 'Tumor_type', 'Gender', 'Age_range', 'Stage', 'TNM', 'Pathological_subtype', 'Molecular_status', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_tissue', 'Final_sample_id', 'Final_patient_age', 'Final_patient_stage', 'Final_patient_treatment'
    var: 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'mean', 'std'
    uns: 'scrublet', 'log1p', 'pca', 'neighbors', 'umap', 'CellType_colors', 'PatientNumber_colors', 'TumorType_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [62]:
ad.write_h5ad('../../Data/Cancer_cell_data_reprocessed/2102-Breastcancer.BRCA.h5ad', compression='gzip')

## Single cell profiling of primary and paired metastatic lymph node tumors in breast cancer patients

Paper: https://www.nature.com/articles/s41467-022-34581-2#data-availability

Data downloaded from: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE167036

Link: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE167036

In [64]:
# Set the project directory
project_dir = "../../Data/BRCA/GSE167036/"  # <- change this for each project

# Load and preprocess
ad = load_and_preprocess_project(project_dir, 
                                 metadata_idx_key='cell_id', 
                                 Project_ID='GSE167036',
                                 further_pre=True)
ad

../../Data/BRCA/GSE167036/GSE167036_cell_counts_matrix.mtx
../../Data/BRCA/GSE167036/GSE167036_barcodes.csv
../../Data/BRCA/GSE167036/GSE167036_features.csv
../../Data/BRCA/GSE167036/GSE167036_meta_all.csv
Loading: ../../Data/BRCA/GSE167036/GSE167036_cell_counts_matrix.mtx

        Unnamed: 0               cell_id
0                1  CA1_AAACCTGAGAGGTAGA
1                2  CA1_AAACCTGAGCCCAACC
2                3  CA1_AAACCTGAGCGTTTAC
3                4  CA1_AAACCTGAGTCCGTAT
4                5  CA1_AAACCTGCAAGTAATG
...            ...                   ...
118840      118841  LN8_TTTGTCAGTCTCTCGT
118841      118842  LN8_TTTGTCAGTGGTCCGT
118842      118843  LN8_TTTGTCATCAAGATCC
118843      118844  LN8_TTTGTCATCACCGTAA
118844      118845  LN8_TTTGTCATCATTTGGG

[118845 rows x 2 columns]

       Unnamed: 0           x
0               1  AL627309.1
1               2  AL669831.5
2               3      FAM87B
3               4   LINC00115
4               5  AL645608.7
...           ...         ...
25296       25297   LINC00898
25297       25298   LINC01692
25298       25299   KRTAP19-8
25299       25300       CRYAA
25300       25301    LRRC3-DT

[25301 rows x 2 columns]

,AL627309.1,AL669831.5,FAM87B,LINC00115,AL645608.7,AL645608.3,AL645608.1,SAMD11,NOC2L,KLHL17,...,AC003682.1,AC008079.1,AC246793.1,GGTLC2,AL021877.2,LINC00898,LINC01692,KRTAP19-8,CRYAA,LRRC3-DT
CA1_AAACCTGAGAGGTAGA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CA1_AAACCTGAGCCCAACC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CA1_AAACCTGAGCGTTTAC,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CA1_AAACCTGAGTCCGTAT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CA1_AAACCTGCAAGTAATG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LN8_TTTGTCAGTCTCTCGT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LN8_TTTGTCAGTGGTCCGT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LN8_TTTGTCATCAAGATCC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LN8_TTTGTCATCACCGTAA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LN8_TTTGTCATCATTTGGG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Running doublet detection on 118845 cells...

/home/wang3712/.local/lib/python3.8/site-packages/scanpy/preprocessing/_normalization.py:170: UserWarning: Received a view of an AnnData. Making a copy.
  view_to_actual(adata)

Automatically set threshold at doublet score = 0.78
Detected doublet rate = 0.0%
Estimated detectable doublet fraction = 1.7%
Overall doublet rate:
	Expected   = 6.0%
	Estimated  = 0.6%
  Detected 13 doublets (0.0%)
  After doublet removal: 118832 cells
Finished processing GSE167036. Shape: (116204, 25301)

AnnData object with n_obs × n_vars = 116204 × 25301
    obs: 'Unnamed: 0', 'cell_id', 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'qc', 'scrublet_doublet', 'sample_type', 'patient_id', 'leiden', 'cell_label', 'main_label', 'ER_statu', 'Her2_statu', 'Grade', 'umap_1', 'umap_2', 'doublet_score', 'predicted_doublet', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'Project_ID', 'Primary_or_Metastatic'
    var: 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'mean', 'std'
    uns: 'scrublet', 'log1p', 'pca', 'neighbors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [ ]:
sc.pl.umap(ad, color=['sample_type'])
sc.pl.umap(ad, color=['patient_id'])

sc.pl.umap(ad, color=['orig.ident'])

sc.pl.umap(ad, color=['cell_label'])

sc.pl.umap(ad, color=['main_label'])

In [66]:
ad = filter_and_recompute(adata=ad, 
                          celltype_col='main_label', 
                          celltypes_to_keep=['Epithelial Cells'],
                          further_pre=True)

Original shape: (116204, 25301)
Filtered shape: (16266, 25301)
Recalculated PCA and UMAP.

In [ ]:
sc.pl.umap(ad, color=['sample_type'])
sc.pl.umap(ad, color=['patient_id'])

sc.pl.umap(ad, color=['orig.ident'])

sc.pl.umap(ad, color=['cell_label'])

sc.pl.umap(ad, color=['main_label'])

In [68]:
ad

AnnData object with n_obs × n_vars = 16266 × 25301
    obs: 'Unnamed: 0', 'cell_id', 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'qc', 'scrublet_doublet', 'sample_type', 'patient_id', 'leiden', 'cell_label', 'main_label', 'ER_statu', 'Her2_statu', 'Grade', 'umap_1', 'umap_2', 'doublet_score', 'predicted_doublet', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'Project_ID', 'Primary_or_Metastatic'
    var: 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'mean', 'std'
    uns: 'scrublet', 'log1p', 'pca', 'neighbors', 'umap', 'sample_type_colors', 'patient_id_colors', 'orig.ident_colors', 'cell_label_colors', 'main_label_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [69]:
# sc.pl.umap(ad, color=['ER_statu'])
# sc.pl.umap(ad, color=['Her2_statu'])

In [70]:
def combined_label(row):
    er = row['ER_statu']
    her2 = row['Her2_statu']
    
    if er == "positive" and her2 == "positive":
        return "HER2+/ER+"
    elif er == "positive" and her2 == "Negative":
        return "ER+"
    elif er == "Negative" and her2 == "positive":
        return "HER2+"
    elif er == "Negative" and her2 == "Negative":
        return "HER2-/ER-"
    else:
        return np.nan  # handle any missing or undefined combinations

In [71]:
ad.obs['sample_type']

CA1_AAACCTGTCTAACTGG         Tumor
CA1_AAACGGGTCCTATTCA         Tumor
CA1_AAACGGGTCTCGATGA         Tumor
CA1_AAATGCCCACATTTCT         Tumor
CA1_AAATGCCCAGATCGGA         Tumor
                           ...
LN8_TTTGCGCCAATTGCTG    Lymph Node
LN8_TTTGCGCTCAAGGTAA    Lymph Node
LN8_TTTGCGCTCAGTTTGG    Lymph Node
LN8_TTTGGTTGTTACGTCA    Lymph Node
LN8_TTTGTCACACAAGCCC    Lymph Node
Name: sample_type, Length: 16266, dtype: category
Categories (2, object): ['Lymph Node', 'Tumor']

In [72]:
new_bc_tissue = []
for tissue in ad.obs['sample_type']:
    if tissue == 'Lymph Node':
        new_bc_tissue.append('Lymph node')
    elif tissue == 'Tumor':
        new_bc_tissue.append('Breast')
    else:
        print('Wrong')

In [73]:
ad.obs['Final_cancer_type'] = 'Breast Cancer'
ad.obs['Final_histological_subtype'] = 'Invasive ductal carcinoma'
ad.obs['Final_molecular_subtype'] = ad.obs.apply(combined_label, axis=1)
ad.obs['Final_tissue'] = new_bc_tissue
ad.obs['Final_sample_id'] = ad.obs['patient_id']

In [74]:
ad.obs['Primary_or_Metastatic'] = 'Metastatic'

In [75]:
# add more clinical information
ad.obs['Final_patient_age'] = 'Unknown'
ad.obs['Final_patient_stage'] = 'Unknown'
ad.obs['Final_patient_treatment'] = 'Naïve'

In [76]:
ad.raw.shape

(16266, 25301)

In [77]:
ad.write_h5ad('../../Data/Cancer_cell_data_reprocessed/GSE167036.BRCA.h5ad', compression='gzip')

## A single‐cell RNA expression atlas of normal, preneoplastic and tumorigenic states in the human breast

Paper: https://www.embopress.org/doi/full/10.15252/embj.2020107333

Data downloaded from: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE161529

Link: https://figshare.com/articles/dataset/Data_R_code_and_output_Seurat_Objects_for_single_cell_RNA-seq_analysis_of_human_breast_tissues/17058077?file=31544843 (HumanBreast10X.zip)

https://figshare.com/articles/dataset/Data_R_code_and_output_Seurat_Objects_for_single_cell_RNA-seq_analysis_of_human_breast_tissues/17058077?file=31546559

In [78]:
data_dir = '../../Data/BRCA/GSE161529/GSE161529_RDS/'
all_h5_files = [i for i in os.listdir(data_dir) if i.endswith('ad') ]
all_h5_files.sort()
all_h5_files

['SeuratObject_ERTotal.h5ad',
 'SeuratObject_ERTotalTum.h5ad',
 'SeuratObject_HER2.h5ad',
 'SeuratObject_HER2Tum.h5ad',
 'SeuratObject_TNBC.h5ad',
 'SeuratObject_TNBCTum.h5ad',
 'SeuratObject_TumLN.ER-0040.h5ad',
 'SeuratObject_TumLN.ER-0043.h5ad',
 'SeuratObject_TumLN.ER-0056.h5ad',
 'SeuratObject_TumLN.ER-0064.h5ad',
 'SeuratObject_TumLN.ER-0167.h5ad',
 'SeuratObject_TumLN.ER-0173.h5ad',
 'SeuratObject_TumLN.mER-0068.h5ad']

In [79]:
ad_list = []
for f in all_h5_files:
    if not f.__contains__('Tum'):
        print(data_dir+f)
        # continue
        ad = sc.read_h5ad(data_dir+f)
        print(ad)
        ad.raw.var.index = ad.raw.var['_index']

        ad.obs['Project_ID'] = 'GSE161529_'+f.split('_')[-1].split('.')[0].replace('Total', '')
        ad.obs['Primary_or_Metastatic'] = 'Primary'
        #ad = reprocess_from_raw_layer(ad, 
        #                              Project_ID='GSE161529_'+f.split('_')[-1].split('.')[0].replace('Total', ''), 
        #                              Primary_or_Metastatic='Primary')
        ad.obs['seurat_clusters'] =ad.obs['seurat_clusters'].astype(str)
        #sc.pl.umap(ad, color=['seurat_clusters', 'group'])
        tum_ad = sc.read_h5ad(data_dir+f.replace('.h5ad', 'Tum.h5ad'))
        print(tum_ad)
        # keep only tumor cells
        ad = ad[ad.obs_names.isin(set(tum_ad.obs_names))]
        print(ad)
        # ad = recompute_pca_and_umap(ad)
        # sc.pl.umap(ad, color=['seurat_clusters', 'group'])
        ad.obs['Final_cancer_type'] = 'Breast Cancer'
        ad.obs['Final_histological_subtype'] = 'N/A'
        ad.obs['Final_molecular_subtype'] = f.split('_')[-1].split('.')[0].replace('Total', '+')
        ad.obs['Final_tissue'] = 'Breast'
        ad.obs['Final_sample_id'] =  ad.obs.group
        print(ad.obs.group)
        print(f.split('_')[-1].split('.')[0].replace('Total', ''))

        ad_list.append(ad)
        # display(ad.to_df())
        print(ad)
        print(ad.raw.shape)

../../Data/BRCA/GSE161529/GSE161529_RDS/SeuratObject_ERTotal.h5ad
AnnData object with n_obs × n_vars = 63555 × 15154
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
AnnData object with n_obs × n_vars = 41850 × 15372
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.05', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
View of AnnData object with n_obs × n_vars = 41850 × 15154
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic'
    var: 'features'
    obsm: 'X_tsne'

/tmp/ipykernel_1351101/75228649.py:24: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  ad.obs['Final_cancer_type'] = 'Breast Cancer'

ER_0114_T3_AAACCTGCAATGGTCT-1    ER_0114_T3
ER_0114_T3_AAACCTGCAGCTGCTG-1    ER_0114_T3
ER_0114_T3_AAACCTGGTAACGTTC-1    ER_0114_T3
ER_0114_T3_AAACCTGGTAGCTGCC-1    ER_0114_T3
ER_0114_T3_AAACCTGTCACGGTTA-1    ER_0114_T3
                                    ...
ER_0163_TTTGGTTGTTAAGGGC-1          ER_0163
ER_0163_TTTGGTTTCTCAGAAC-1          ER_0163
ER_0163_TTTGTTGAGGTTCTAC-1          ER_0163
ER_0163_TTTGTTGCATCGCTGG-1          ER_0163
ER_0163_TTTGTTGGTCGCACGT-1          ER_0163
Name: group, Length: 41850, dtype: object
ER
AnnData object with n_obs × n_vars = 41850 × 15154
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_tissue', 'Final_sample_id'
    var: 'features'
    obsm: 'X_tsne'
(41850, 15154)
../../Data/BRCA/GSE161529/GSE161529_RDS/SeuratObject_HER2.h5ad
AnnData object with n_obs × n_vars = 31918 × 14705
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.07', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
AnnData object with n_obs × n_vars = 17849 × 14531
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.05', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
View of AnnData object with n_obs × n_vars = 17849 × 14705
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.07', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic'
    var: 'features'
    obsm: 'X_tsne'

/tmp/ipykernel_1351101/75228649.py:24: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  ad.obs['Final_cancer_type'] = 'Breast Cancer'

HER2_0031_AAACCTGAGACTCGGA-1    HER2_0031
HER2_0031_AAACCTGAGGGCACTA-1    HER2_0031
HER2_0031_AAACCTGAGTGAACGC-1    HER2_0031
HER2_0031_AAACCTGCAAGGGTCA-1    HER2_0031
HER2_0031_AAACCTGCAATCAGAA-1    HER2_0031
                                  ...
HER2_0176_TTTGTTGCAATCTCTT-1    HER2_0176
HER2_0176_TTTGTTGCATGGATCT-1    HER2_0176
HER2_0176_TTTGTTGGTACTCGCG-1    HER2_0176
HER2_0176_TTTGTTGGTATTGGCT-1    HER2_0176
HER2_0176_TTTGTTGTCATTCTTG-1    HER2_0176
Name: group, Length: 17849, dtype: object
HER2
AnnData object with n_obs × n_vars = 17849 × 14705
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.07', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_tissue', 'Final_sample_id'
    var: 'features'
    obsm: 'X_tsne'
(17849, 14705)
../../Data/BRCA/GSE161529/GSE161529_RDS/SeuratObject_TNBC.h5ad
AnnData object with n_obs × n_vars = 54820 × 15403
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
AnnData object with n_obs × n_vars = 30353 × 16325
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
View of AnnData object with n_obs × n_vars = 30353 × 15403
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic'
    var: 'features'
    obsm: 'X_tsne'

/tmp/ipykernel_1351101/75228649.py:24: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  ad.obs['Final_cancer_type'] = 'Breast Cancer'

TN_B1_0554_AAACCCACACCGTGCA-1    TN_B1_0554
TN_B1_0554_AAACCCAGTTGGGATG-1    TN_B1_0554
TN_B1_0554_AAACCCATCGCCACTT-1    TN_B1_0554
TN_B1_0554_AAACGAAGTACTGCGC-1    TN_B1_0554
TN_B1_0554_AAACGAAGTCGATTAC-1    TN_B1_0554
                                    ...
TN_0114_T2_TTGACTTTCACCTCGT-1    TN_0114_T2
TN_0114_T2_TTGGCAATCATGGTCA-1    TN_0114_T2
TN_0114_T2_TTTATGCCATAACCTG-1    TN_0114_T2
TN_0114_T2_TTTCCTCCACGAAGCA-1    TN_0114_T2
TN_0114_T2_TTTGGTTTCTCGGACG-1    TN_0114_T2
Name: group, Length: 30353, dtype: object
TNBC
AnnData object with n_obs × n_vars = 30353 × 15403
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_tissue', 'Final_sample_id'
    var: 'features'
    obsm: 'X_tsne'
(30353, 15403)

In [80]:
# process the lymph node samples
for f in all_h5_files:
    if f.__contains__('TumLN'):
        print(data_dir+f)        
        ad = sc.read_h5ad(data_dir+f)
        print(ad)
        ad.raw.var.index = ad.raw.var['_index']
        # ad = reprocess_from_raw_layer(ad, 
        #                               Project_ID='GSE161529_LN', 
        #                               Primary_or_Metastatic='Metastatic')
        # break
        # ad = ad[~ad.obs.group.str.endswith('_T')]
        ad.obs['Project_ID'] = 'GSE161529_LN'
        ad.obs['Primary_or_Metastatic'] = 'Metastatic'
        ad.obs['seurat_clusters'] =ad.obs['seurat_clusters'].astype(str)
        
        ad.obs['Final_cancer_type'] = 'Breast Cancer'
        ad.obs['Final_histological_subtype'] = 'N/A'
        ad.obs['Final_molecular_subtype'] = 'ER+'
        # ad.obs['Final_tissue'] = 'Lymph Node'
        ad.obs['Final_sample_id'] =  ad.obs.group
        tissues = []
        for group in ad.obs.group:
            if group.endswith('_T'):
                tissues.append('Breast')
            elif group.endswith('_LN'):
                tissues.append('Lymph Node')
            else:
                print(group)
        ad.obs['Final_tissue'] = tissues
        # ad[ad.obs.group.str.endswith('_T')].obs['Final_tissue'] = 'Breast'
        
        print(f.split('_')[-1].split('.')[0].replace('Total', ''))

        # display(ad.to_df())
        ad_list.append(ad)
        print(ad)
        print(ad.raw.shape)

../../Data/BRCA/GSE161529/GSE161529_RDS/SeuratObject_TumLN.ER-0040.h5ad
AnnData object with n_obs × n_vars = 11565 × 11639
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
TumLN
AnnData object with n_obs × n_vars = 11565 × 11639
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_sample_id', 'Final_tissue'
    var: 'features'
    obsm: 'X_tsne'
(11565, 11639)
../../Data/BRCA/GSE161529/GSE161529_RDS/SeuratObject_TumLN.ER-0043.h5ad
AnnData object with n_obs × n_vars = 4930 × 12423
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.05', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
TumLN
AnnData object with n_obs × n_vars = 4930 × 12423
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.05', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_sample_id', 'Final_tissue'
    var: 'features'
    obsm: 'X_tsne'
(4930, 12423)
../../Data/BRCA/GSE161529/GSE161529_RDS/SeuratObject_TumLN.ER-0056.h5ad
AnnData object with n_obs × n_vars = 9315 × 9021
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
TumLN
AnnData object with n_obs × n_vars = 9315 × 9021
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_sample_id', 'Final_tissue'
    var: 'features'
    obsm: 'X_tsne'
(9315, 9021)
../../Data/BRCA/GSE161529/GSE161529_RDS/SeuratObject_TumLN.ER-0064.h5ad
AnnData object with n_obs × n_vars = 5931 × 11206
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.05', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
TumLN
AnnData object with n_obs × n_vars = 5931 × 11206
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.05', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_sample_id', 'Final_tissue'
    var: 'features'
    obsm: 'X_tsne'
(5931, 11206)
../../Data/BRCA/GSE161529/GSE161529_RDS/SeuratObject_TumLN.ER-0167.h5ad
AnnData object with n_obs × n_vars = 11406 × 12850
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
TumLN
AnnData object with n_obs × n_vars = 11406 × 12850
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_sample_id', 'Final_tissue'
    var: 'features'
    obsm: 'X_tsne'
(11406, 12850)
../../Data/BRCA/GSE161529/GSE161529_RDS/SeuratObject_TumLN.ER-0173.h5ad
AnnData object with n_obs × n_vars = 11023 × 14153
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
TumLN
AnnData object with n_obs × n_vars = 11023 × 14153
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_sample_id', 'Final_tissue'
    var: 'features'
    obsm: 'X_tsne'
(11023, 14153)
../../Data/BRCA/GSE161529/GSE161529_RDS/SeuratObject_TumLN.mER-0068.h5ad
AnnData object with n_obs × n_vars = 5522 × 8365
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters'
    var: 'features'
    obsm: 'X_tsne'
TumLN
AnnData object with n_obs × n_vars = 5522 × 8365
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'integrated_snn_res.0.1', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_sample_id', 'Final_tissue'
    var: 'features'
    obsm: 'X_tsne'
(5522, 8365)

In [81]:
all_sample_num = 0
for ad in ad_list:
    all_sample_num += ad.n_obs
all_sample_num

149744

In [82]:
combined_ad = ann.concat(ad_list, join="inner", axis=0)
combined_ad

/home/wang3712/.local/lib/python3.8/site-packages/anndata/_core/anndata.py:1838: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/home/wang3712/.local/lib/python3.8/site-packages/anndata/_core/anndata.py:1838: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

AnnData object with n_obs × n_vars = 149744 × 7361
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_tissue', 'Final_sample_id'
    obsm: 'X_tsne'

In [83]:
import numpy as np
import pandas as pd
from scipy.sparse import issparse

# Step 1: Find duplicated obs_names
duplicated_obs = combined_ad.obs_names[combined_ad.obs_names.duplicated()]

if len(duplicated_obs) == 0:
    print("✅ No duplicated obs_names found.")
else:
    print(f"🔍 Found {len(duplicated_obs)} duplicated obs_names.\n")
    '''
    for obs_name in tqdm(duplicated_obs.unique()):
        indices = np.where(combined_ad.obs_names == obs_name)[0]
        exprs = combined_ad.X[indices]

        if issparse(exprs):
            exprs_array = exprs.toarray()
        else:
            exprs_array = exprs

        # Compare all rows to the first row
        all_equal = np.all(exprs_array == exprs_array[0], axis=1).all()
        if not all_equal:
            print(obs_name)
        # print(f"{obs_name}: {'✅ Identical' if all_equal else '❌ Different'}")
    '''

🔍 Found 12684 duplicated obs_names.

In [84]:
import pandas as pd

# Step 1: Backup the original obs_names
original_obs_names = combined_ad.obs_names.copy()

# Step 2: Assign temporary unique index to avoid conflict during filtering
combined_ad.obs_names = pd.Index([f"{i}_{name}" for i, name in enumerate(original_obs_names)])

# Step 3: Add original name into .obs for filtering
combined_ad.obs["original_obs_name"] = original_obs_names

# Step 4: Sort so 'Metastatic' comes first
obs_df = combined_ad.obs.sort_values(by="Primary_or_Metastatic", ascending=True)

# Step 5: Drop duplicates on the original obs name (keeping 'Metastatic' if it exists)
obs_dedup = obs_df.drop_duplicates(subset="original_obs_name", keep="first")

obs_dedup

,orig.ident,nCount_RNA,nFeature_RNA,group,seurat_clusters,Project_ID,Primary_or_Metastatic,Final_cancer_type,Final_histological_subtype,Final_molecular_subtype,Final_tissue,Final_sample_id,original_obs_name
149743_mER_0068_LN_TTTGTCATCGCAAACT-1,mER,1795.0,828,mER_0068_LN,2,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,mER_0068_LN,mER_0068_LN_TTTGTCATCGCAAACT-1
109954_ER_0056_LN_ACTGTCCAGCTGCGAA-1,ER,1294.0,519,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,ER_0056_LN_ACTGTCCAGCTGCGAA-1
109953_ER_0056_LN_ACTGCTCTCAAGCCTA-1,ER,1646.0,769,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,ER_0056_LN_ACTGCTCTCAAGCCTA-1
109952_ER_0056_LN_ACTGCTCGTACTTCTT-1,ER,1020.0,518,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,ER_0056_LN_ACTGCTCGTACTTCTT-1
109951_ER_0056_LN_ACTGCTCCATGCCTAA-1,ER,1206.0,558,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,ER_0056_LN_ACTGCTCCATGCCTAA-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49916_HER2_0308_GTTCGGGTCCGCAAGC-1,HER2,8347.0,2870,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,HER2_0308_GTTCGGGTCCGCAAGC-1
49917_HER2_0308_GTTCTCGCACCGAATT-1,HER2,13390.0,3950,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,HER2_0308_GTTCTCGCACCGAATT-1
49918_HER2_0308_GTTCTCGGTCGGCACT-1,HER2,13129.0,3380,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,HER2_0308_GTTCTCGGTCGGCACT-1
49902_HER2_0308_GTTCATTAGTGACATA-1,HER2,2703.0,1275,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,HER2_0308_GTTCATTAGTGACATA-1
74871_TN_0135_TACAGTGTCGGAAACG-1,TN,3980.0,1668,TN_0135,2,GSE161529_TNBC,Primary,Breast Cancer,N/A,TNBC,Breast,TN_0135,TN_0135_TACAGTGTCGGAAACG-1

In [85]:
# Step 6: Subset the AnnData object using unique (temporary) obs_names
print(combined_ad)
combined_ad = combined_ad[obs_dedup.index].copy()

# Step 7: Restore the original obs_names (if needed)
combined_ad.obs_names = combined_ad.obs["original_obs_name"]
combined_ad.obs.drop(columns="original_obs_name", inplace=True)
combined_ad

AnnData object with n_obs × n_vars = 149744 × 7361
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_tissue', 'Final_sample_id', 'original_obs_name'
    obsm: 'X_tsne'

AnnData object with n_obs × n_vars = 137060 × 7361
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_tissue', 'Final_sample_id'
    obsm: 'X_tsne'

In [86]:
patient_clinical_df = pd.read_csv('../../Data/BRCA/GSE161529/Patient_clinical.txt', sep='\t')
patient_clinical_df

    Specimen ID  Patient Age      Tumor Type Tumor Size (mm) Grade
0       TN-0126           64            TNBC              64     3
1       TN-0135           61            TNBC              22     3
2       TN-0106           65            TNBC              25     3
3    TN-0114-T2           84            TNBC              17     3
4    TN-B1-4031           25    TNBC (BRCA1)              20     3
5    TN-B1-0131           84    TNBC (BRCA1)              25     3
6    TN-B1-0554           29    TNBC (BRCA1)              37     3
7    TN-B1-0177           30    TNBC (BRCA1)              13     3
8     HER2-0308           32  HER2 amplified              20     3
9     HER2-0337           66  HER2 amplified              67     3
10    HER2-0031           47  HER2 amplified              18     3
11    HER2-0069           71  HER2 amplified              27     3
12    HER2-0161           80  HER2 amplified              45     3
13    HER2-0176           60  HER2 amplified              20     3
14      ER-0319           58             PR+              27     3
15      ER-0001           58             ER+              32     3
16      ER-0125           45             ER+              48     2
17      ER-0360           70             ER+              50     2
18   ER-0114-T3           84             ER+              20     1
19      ER-0032           55             ER+              90     3
20      ER-0042           58             ER+              18     2
21      ER-0025           52             ER+              23     2
22      ER-0151           49             ER+              35     2
23      ER-0163           45             ER+              45     3
24   ER-0029-7C           59             ER+               8     1
25   ER-0029-9C           59             ER+              38     1
26    ER-0040-T           69             ER+              50     3
27   ER-0040-LN           69             ER+              17     3
28    ER-0043-T           55             ER+              55     3
29   ER-0043-LN           55             ER+               -     -
30    ER-0056-T           66             ER+              45     2
31   ER-0056-LN           66             ER+              12     -
32    ER-0064-T           65             ER+              70     2
33   ER-0064-LN           65             ER+              25     -
34    ER-0167-T           83             ER+              34     3
35   ER-0167-LN           83             ER+              25     -
36    ER-0173-T           83             ER+              38     3
37   ER-0173-LN           83             ER+              13     -
38     mER-0178           84             ER+              58     3
39   mER-0068-T           79             ER+              33     3
40  mER-0068-LN           79             ER+              21     -

In [87]:
np.unique(combined_ad.obs.Final_sample_id)

array(['ER_0001', 'ER_0025', 'ER_0032', 'ER_0040_LN', 'ER_0040_T',
       'ER_0042', 'ER_0043_LN', 'ER_0043_T', 'ER_0056_LN', 'ER_0056_T',
       'ER_0064_LN', 'ER_0064_T', 'ER_0114_T3', 'ER_0125', 'ER_0151',
       'ER_0163', 'ER_0167_LN', 'ER_0167_T', 'ER_0173_LN', 'ER_0173_T',
       'ER_0319', 'ER_0360', 'HER2_0031', 'HER2_0069', 'HER2_0161',
       'HER2_0176', 'HER2_0308', 'HER2_0337', 'TN_0106', 'TN_0114_T2',
       'TN_0126', 'TN_0135', 'TN_B1_0131', 'TN_B1_0177', 'TN_B1_0554',
       'TN_B1_4031', 'mER_0068_LN', 'mER_0068_T'], dtype=object)

In [88]:
# Step 1: Reset index for merging, but save cell IDs
combined_ad.obs['tmp_donor_id'] = [i.lower().replace('_', '-') for i in combined_ad.obs.Final_sample_id]
patient_clinical_df['Case ID'] = [i.lower().replace('_', '-') for i in patient_clinical_df['Specimen ID']]

In [89]:
combined_ad.obs

,orig.ident,nCount_RNA,nFeature_RNA,group,seurat_clusters,Project_ID,Primary_or_Metastatic,Final_cancer_type,Final_histological_subtype,Final_molecular_subtype,Final_tissue,Final_sample_id,tmp_donor_id
original_obs_name,,,,,,,,,,,,,
mER_0068_LN_TTTGTCATCGCAAACT-1,mER,1795.0,828,mER_0068_LN,2,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,mER_0068_LN,mer-0068-ln
ER_0056_LN_ACTGTCCAGCTGCGAA-1,ER,1294.0,519,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,er-0056-ln
ER_0056_LN_ACTGCTCTCAAGCCTA-1,ER,1646.0,769,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,er-0056-ln
ER_0056_LN_ACTGCTCGTACTTCTT-1,ER,1020.0,518,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,er-0056-ln
ER_0056_LN_ACTGCTCCATGCCTAA-1,ER,1206.0,558,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,er-0056-ln
...,...,...,...,...,...,...,...,...,...,...,...,...,...
HER2_0308_GTTCGGGTCCGCAAGC-1,HER2,8347.0,2870,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,her2-0308
HER2_0308_GTTCTCGCACCGAATT-1,HER2,13390.0,3950,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,her2-0308
HER2_0308_GTTCTCGGTCGGCACT-1,HER2,13129.0,3380,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,her2-0308
HER2_0308_GTTCATTAGTGACATA-1,HER2,2703.0,1275,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,her2-0308
TN_0135_TACAGTGTCGGAAACG-1,TN,3980.0,1668,TN_0135,2,GSE161529_TNBC,Primary,Breast Cancer,N/A,TNBC,Breast,TN_0135,tn-0135

In [90]:
merged = combined_ad.obs.reset_index().merge(
    patient_clinical_df,
    left_on='tmp_donor_id',
    right_on='Case ID',
    how='left'
)

# Step 2: Restore original index (cell barcodes)
merged = merged.set_index('original_obs_name')

# Step 3: Assign back
combined_ad.obs = merged
combined_ad

AnnData object with n_obs × n_vars = 137060 × 7361
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'group', 'seurat_clusters', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_tissue', 'Final_sample_id', 'tmp_donor_id', 'Specimen ID', 'Patient Age', 'Tumor Type', 'Tumor Size (mm)', 'Grade', 'Case ID'
    obsm: 'X_tsne'

In [91]:
combined_ad.obs

,orig.ident,nCount_RNA,nFeature_RNA,group,seurat_clusters,Project_ID,Primary_or_Metastatic,Final_cancer_type,Final_histological_subtype,Final_molecular_subtype,Final_tissue,Final_sample_id,tmp_donor_id,Specimen ID,Patient Age,Tumor Type,Tumor Size (mm),Grade,Case ID
original_obs_name,,,,,,,,,,,,,,,,,,,
mER_0068_LN_TTTGTCATCGCAAACT-1,mER,1795.0,828,mER_0068_LN,2,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,mER_0068_LN,mer-0068-ln,mER-0068-LN,79,ER+,21,-,mer-0068-ln
ER_0056_LN_ACTGTCCAGCTGCGAA-1,ER,1294.0,519,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,er-0056-ln,ER-0056-LN,66,ER+,12,-,er-0056-ln
ER_0056_LN_ACTGCTCTCAAGCCTA-1,ER,1646.0,769,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,er-0056-ln,ER-0056-LN,66,ER+,12,-,er-0056-ln
ER_0056_LN_ACTGCTCGTACTTCTT-1,ER,1020.0,518,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,er-0056-ln,ER-0056-LN,66,ER+,12,-,er-0056-ln
ER_0056_LN_ACTGCTCCATGCCTAA-1,ER,1206.0,558,ER_0056_LN,0,GSE161529_LN,Metastatic,Breast Cancer,N/A,ER+,Lymph Node,ER_0056_LN,er-0056-ln,ER-0056-LN,66,ER+,12,-,er-0056-ln
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HER2_0308_GTTCGGGTCCGCAAGC-1,HER2,8347.0,2870,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,her2-0308,HER2-0308,32,HER2 amplified,20,3,her2-0308
HER2_0308_GTTCTCGCACCGAATT-1,HER2,13390.0,3950,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,her2-0308,HER2-0308,32,HER2 amplified,20,3,her2-0308
HER2_0308_GTTCTCGGTCGGCACT-1,HER2,13129.0,3380,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,her2-0308,HER2-0308,32,HER2 amplified,20,3,her2-0308
HER2_0308_GTTCATTAGTGACATA-1,HER2,2703.0,1275,HER2_0308,0,GSE161529_HER2,Primary,Breast Cancer,N/A,HER2,Breast,HER2_0308,her2-0308,HER2-0308,32,HER2 amplified,20,3,her2-0308
TN_0135_TACAGTGTCGGAAACG-1,TN,3980.0,1668,TN_0135,2,GSE161529_TNBC,Primary,Breast Cancer,N/A,TNBC,Breast,TN_0135,tn-0135,TN-0135,61,TNBC,22,3,tn-0135

In [92]:
all_sample_id = np.unique(combined_ad.obs['Final_sample_id'])
mets_sample = set()
for sample_id in all_sample_id:
    if sample_id.__contains__('_T'):
        if sample_id.replace('_T', '_LN') in all_sample_id:
            print(sample_id)
            mets_sample.add(sample_id)
mets_sample = list(mets_sample)
mets_sample.sort()

ER_0040_T
ER_0043_T
ER_0056_T
ER_0064_T
ER_0167_T
ER_0173_T
mER_0068_T

In [93]:
mets_sample

['ER_0040_T',
 'ER_0043_T',
 'ER_0056_T',
 'ER_0064_T',
 'ER_0167_T',
 'ER_0173_T',
 'mER_0068_T']

In [94]:
primary_or_metastatic = []
for sample in mets_sample:
    print(sample)
    print(np.unique(combined_ad[combined_ad.obs['Final_sample_id']==sample].obs['Primary_or_Metastatic']))
    print(np.unique(combined_ad[combined_ad.obs['Final_sample_id']==sample].obs['Final_tissue']))

ER_0040_T
['Metastatic']
['Breast']
ER_0043_T
['Metastatic']
['Breast']
ER_0056_T
['Metastatic']
['Breast']
ER_0064_T
['Metastatic']
['Breast']
ER_0167_T
['Metastatic']
['Breast']
ER_0173_T
['Metastatic']
['Breast']
mER_0068_T
['Metastatic']
['Breast']

In [95]:
# add more clinical information
combined_ad.obs['Final_patient_age'] = combined_ad.obs['Patient Age']
combined_ad.obs['Final_patient_stage'] = 'Unknown'
combined_ad.obs['Final_patient_treatment'] = 'Naïve'

In [96]:
combined_ad.obs['Project_ID'] = 'GSE161529'

In [97]:
combined_ad.write_h5ad('../../Data/Cancer_cell_data_reprocessed/GSE161529.BRCA.h5ad', compression='gzip')

In [98]:
del ad_list, combined_ad

## A single-cell map of intratumoral changes during anti-PD1 treatment of patients with breast cancer

Paper: https://www.nature.com/articles/s41591-021-01323-8#Fig1

Data downloaded from: httpshttps://lambrechtslab.sites.vib.be/en/single-cell

Link: 
- Matrix: https://vib.blob.core.windows.net/vib-forms/Documents/1867-counts_cells_cohort2.rds?sv=2019-07-07&sr=b&sig=mFBRJlKUM8OQDNfD6WKStiVGs3BTa7O3wepBAv%2FHalQ%3D&se=2025-07-10T17%3A04%3A47Z&sp=r
- Patient metadata: https://static-content.springer.com/esm/art%3A10.1038%2Fs41591-021-01323-8/MediaObjects/41591_2021_1323_MOESM1_ESM.pdf

In [12]:
memory_usgae()

Current memory usage: 0.65 GB

In [13]:
# Set the project directory
project_dir = "../../Data/BRCA/Single_cell_map_anti-PD1/cohort1/"  # <- change this for each project

# Load and preprocess
ad = load_and_preprocess_project(project_dir, 
                                 metadata_idx_key='Cell', 
                                 Project_ID='Single_cell_map_anti-PD1',
                                 further_pre=False)
ad

../../Data/BRCA/Single_cell_map_anti-PD1/cohort1/1863-counts_cells_cohort1.matrix.mtx
../../Data/BRCA/Single_cell_map_anti-PD1/cohort1/1863-counts_cells_cohort1.barcodes.txt
../../Data/BRCA/Single_cell_map_anti-PD1/cohort1/1863-counts_cells_cohort1.genes.txt
../../Data/BRCA/Single_cell_map_anti-PD1/cohort1/1872-BIOKEY_metaData_cohort1_web.csv
Loading: ../../Data/BRCA/Single_cell_map_anti-PD1/cohort1/1863-counts_cells_cohort1.matrix.mtx

                                   Cells
0       BIOKEY_13_Pre_AAACCTGCAACAACCT-1
1       BIOKEY_13_Pre_AAACCTGCAAGAAGAG-1
2       BIOKEY_13_Pre_AAACCTGGTCTCCACT-1
3       BIOKEY_13_Pre_AAACCTGTCAACGAAA-1
4       BIOKEY_13_Pre_AAACGGGAGAGTAAGG-1
...                                  ...
175937   BIOKEY_24_On_TTTGTCAAGTTCGATC-1
175938   BIOKEY_24_On_TTTGTCACACGACTCG-1
175939   BIOKEY_24_On_TTTGTCACACTCAGGC-1
175940   BIOKEY_24_On_TTTGTCAGTCGCGAAA-1
175941   BIOKEY_24_On_TTTGTCATCGGTTAAC-1

[175942 rows x 1 columns]

          Genes
0          A1BG
1      A1BG-AS1
2           A2M
3       A2M-AS1
4        A4GALT
...         ...
25283       AVP
25284    BPIFA1
25285   OR14A16
25286    PROKR1
25287     SEMG2

[25288 rows x 1 columns]

,A1BG,A1BG-AS1,A2M,A2M-AS1,A4GALT,AAAS,AACS,AADAC,AADACL2-AS1,AADAT,...,AL161752.1,AL355075.1,AL390038.1,AL606970.4,AL845331.2,AVP,BPIFA1,OR14A16,PROKR1,SEMG2
BIOKEY_13_Pre_AAACCTGCAACAACCT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BIOKEY_13_Pre_AAACCTGCAAGAAGAG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BIOKEY_13_Pre_AAACCTGGTCTCCACT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BIOKEY_13_Pre_AAACCTGTCAACGAAA-1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BIOKEY_13_Pre_AAACGGGAGAGTAAGG-1,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BIOKEY_24_On_TTTGTCAAGTTCGATC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BIOKEY_24_On_TTTGTCACACGACTCG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BIOKEY_24_On_TTTGTCACACTCAGGC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BIOKEY_24_On_TTTGTCAGTCGCGAAA-1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BIOKEY_24_On_TTTGTCATCGGTTAAC-1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Running doublet detection on 175942 cells...

/home/wang3712/.local/lib/python3.8/site-packages/scanpy/preprocessing/_normalization.py:170: UserWarning: Received a view of an AnnData. Making a copy.
  view_to_actual(adata)

Automatically set threshold at doublet score = 0.88
Detected doublet rate = 0.0%
Estimated detectable doublet fraction = 0.1%
Overall doublet rate:
	Expected   = 6.0%
	Estimated  = 0.0%
  Detected 0 doublets (0.0%)
  After doublet removal: 175942 cells
Finished processing Single_cell_map_anti-PD1. Shape: (169971, 25288)

AnnData object with n_obs × n_vars = 169971 × 25288
    obs: 'Cell', 'nCount_RNA', 'nFeature_RNA', 'patient_id', 'timepoint', 'expansion', 'BC_type', 'cellType', 'cohort', 'doublet_score', 'predicted_doublet', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'Project_ID', 'Primary_or_Metastatic'
    var: 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'scrublet'

In [14]:
memory_usgae()

Current memory usage: 5.84 GB

In [16]:
file_path = '../../Data/BRCA/Single_cell_map_anti-PD1/cohort2/1867-counts_cells_cohort2.csv'

# Step 1: Read just the first line to get cell names
with open(file_path) as f:
    header = f.readline().strip('').split(',')
cell_names = header[1:]  # skip the gene column
cell_names = [name.strip('"') for name in cell_names]

print(cell_names[:10])
# Step 2: Read file in chunks and store rows
gene_names = []
data = []

['BIOKEY_33_Pre_AAACCTGAGAGACTTA-1', 'BIOKEY_33_Pre_AAACCTGAGTAGCGGT-1', 'BIOKEY_33_Pre_AAACCTGCATGGTAGG-1', 'BIOKEY_33_Pre_AAACCTGGTATAGGGC-1', 'BIOKEY_33_Pre_AAACCTGGTCAGGACA-1', 'BIOKEY_33_Pre_AAACCTGGTGAGGGAG-1', 'BIOKEY_33_Pre_AAACCTGTCCGTCATC-1', 'BIOKEY_33_Pre_AAACCTGTCTCGCATC-1', 'BIOKEY_33_Pre_AAACCTGTCTTGTATC-1', 'BIOKEY_33_Pre_AAACGGGGTCCTCCAT-1']

In [17]:
# count = 0
gene_names = []
data = []
with open(file_path) as f:
    next(f)  # skip header
    for line in tqdm(f, desc="Reading rows"):
        parts = line.strip().split(',')
        gene = parts[0]
        counts = np.array(parts[1:], dtype=np.float32)
        gene_names.append(gene)
        data.append(counts)

gene_names = [name.strip('"') for name in gene_names]
print(gene_names[:10])

# Step 3: Stack into matrix and transpose
dense_matrix = np.vstack(data)  # shape: (genes, cells)
transposed = sp.csr_matrix(dense_matrix.T)  # shape: (cells, genes)

# Step 4: Create AnnData
ad_2 = ann.AnnData(X=transposed,
                   obs=pd.DataFrame(index=cell_names),
                   var=pd.DataFrame(index=gene_names))
ad_2

Reading rows: 22889it [01:34, 241.48it/s]

['A1BG', 'A1BG-AS1', 'A2M', 'A2M-AS1', 'A2ML1', 'A4GALT', 'AAAS', 'AACS', 'AAED1', 'AAGAB']

AnnData object with n_obs × n_vars = 50693 × 22889

In [21]:
ad_2.raw = ad_2

In [22]:
# re-process the adata
ad_2 = reprocess_from_raw_layer(ad_2, 
                                Project_ID='Single_cell_map_anti-PD1', 
                                Primary_or_Metastatic='Primary',
                                remove_doublets=True,
                                further_pre=False)

Running doublet detection on 50693 cells...

/home/wang3712/.local/lib/python3.8/site-packages/scanpy/preprocessing/_normalization.py:170: UserWarning: Received a view of an AnnData. Making a copy.
  view_to_actual(adata)

Automatically set threshold at doublet score = 0.75
Detected doublet rate = 0.0%
Estimated detectable doublet fraction = 0.2%
Overall doublet rate:
	Expected   = 6.0%
	Estimated  = 1.2%
  Detected 1 doublets (0.0%)
  After doublet removal: 50692 cells
Standard filtering...
Reprocessed dataset. Final shape: (49537, 22889)

In [23]:
combined_ad = ann.concat([ad, ad_2], join="inner", axis=0)

In [25]:
del ad, ad_2
memory_usgae()

Current memory usage: 23.82 GB

In [29]:
meta_1 = pd.read_csv('../../Data/BRCA/Single_cell_map_anti-PD1/cohort1/1872-BIOKEY_metaData_cohort1_web.csv', index_col=0)

In [31]:
meta_2 = pd.read_csv('../../Data/BRCA/Single_cell_map_anti-PD1/cohort2/1871-BIOKEY_metaData_cohort2_web.csv', index_col=0)

In [33]:
meta_df = pd.concat([meta_1, meta_2])
meta_df

,nCount_RNA,nFeature_RNA,patient_id,timepoint,expansion,BC_type,cellType,cohort
Cell,,,,,,,,
BIOKEY_13_Pre_AAACCTGCAACAACCT-1,684,430,BIOKEY_13,Pre,NaN,HER2+,Myeloid_cell,treatment_naive
BIOKEY_13_Pre_AAACCTGCAAGAAGAG-1,1252,700,BIOKEY_13,Pre,NaN,HER2+,T_cell,treatment_naive
BIOKEY_13_Pre_AAACCTGGTCTCCACT-1,522,330,BIOKEY_13,Pre,NaN,HER2+,pDC,treatment_naive
BIOKEY_13_Pre_AAACCTGTCAACGAAA-1,8454,2637,BIOKEY_13,Pre,NaN,HER2+,Myeloid_cell,treatment_naive
BIOKEY_13_Pre_AAACGGGAGAGTAAGG-1,1612,874,BIOKEY_13,Pre,NaN,HER2+,Fibroblast,treatment_naive
...,...,...,...,...,...,...,...,...
BIOKEY_42_On_TTTGGTTTCAAACCAC-1,515,246,BIOKEY_42,On,NE,ER+,Fibroblast,neoadjuvant_chemo
BIOKEY_42_On_TTTGGTTTCATTGCGA-1,3477,1447,BIOKEY_42,On,NE,ER+,Fibroblast,neoadjuvant_chemo
BIOKEY_42_On_TTTGTCACAAACTGTC-1,5604,2131,BIOKEY_42,On,NE,ER+,Endothelial_cell,neoadjuvant_chemo
BIOKEY_42_On_TTTGTCACAAAGCGGT-1,8375,3148,BIOKEY_42,On,NE,ER+,Cancer_cell,neoadjuvant_chemo
BIOKEY_42_On_TTTGTCAGTAGTGAAT-1,6954,2509,BIOKEY_42,On,NE,ER+,Fibroblast,neoadjuvant_chemo

In [34]:
combined_ad.obs_names = combined_ad.obs_names.str.strip()
combined_ad.obs_names = combined_ad.obs_names.str.strip('"')

combined_ad.obs_names

Index(['BIOKEY_13_Pre_AAACCTGCAACAACCT-1', 'BIOKEY_13_Pre_AAACCTGCAAGAAGAG-1',
       'BIOKEY_13_Pre_AAACCTGGTCTCCACT-1', 'BIOKEY_13_Pre_AAACCTGTCAACGAAA-1',
       'BIOKEY_13_Pre_AAACGGGAGAGTAAGG-1', 'BIOKEY_13_Pre_AAACGGGCACAGAGGT-1',
       'BIOKEY_13_Pre_AAACGGGCATGGGACA-1', 'BIOKEY_13_Pre_AAACGGGGTTCATGGT-1',
       'BIOKEY_13_Pre_AAACGGGTCAACGAAA-1', 'BIOKEY_13_Pre_AAACGGGTCACCAGGC-1',
       ...
       'BIOKEY_42_On_TTTCCTCCAGTAGAGC-1', 'BIOKEY_42_On_TTTGCGCAGTACGCGA-1',
       'BIOKEY_42_On_TTTGGTTAGAGCAATT-1', 'BIOKEY_42_On_TTTGGTTGTAATAGCA-1',
       'BIOKEY_42_On_TTTGGTTGTGGCCCTA-1', 'BIOKEY_42_On_TTTGGTTTCAAACCAC-1',
       'BIOKEY_42_On_TTTGGTTTCATTGCGA-1', 'BIOKEY_42_On_TTTGTCACAAACTGTC-1',
       'BIOKEY_42_On_TTTGTCACAAAGCGGT-1', 'BIOKEY_42_On_TTTGTCAGTAGTGAAT-1'],
      dtype='object', length=219508)

In [35]:
combined_ad.obs = meta_df.loc[combined_ad.obs_names]

In [36]:
combined_ad.obs['cellType'].value_counts()

cellType
T_cell              71574
Cancer_cell         60517
Fibroblast          36780
Myeloid_cell        22547
B_cell              13970
Endothelial_cell    12038
Mast_cell            1144
pDC                   938
Name: count, dtype: int64

In [37]:
combined_ad = filter_and_recompute(adata=combined_ad, 
                          celltype_col='cellType', 
                          celltypes_to_keep=['Cancer_cell'],
                          further_pre=True)
combined_ad

Original shape: (219508, 22567)
Filtered shape: (60517, 22567)

/home/wang3712/.local/lib/python3.8/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/wang3712/.local/lib/python3.8/site-packages/umap/distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/wang3712/.local/lib/python3.8/site-packages/umap/distances.py:1086: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/wang3712/.local/lib/python3.8/site-packages/umap/umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()

Recalculated PCA and UMAP.

AnnData object with n_obs × n_vars = 60517 × 22567
    obs: 'nCount_RNA', 'nFeature_RNA', 'patient_id', 'timepoint', 'expansion', 'BC_type', 'cellType', 'cohort'
    uns: 'pca', 'neighbors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [ ]:
reset_plot()
sc.pl.umap(combined_ad, color=['cohort', 'BC_type', 'patient_id', 'timepoint'])

In [39]:
patient_clinical_df = pd.read_csv('../../Data/BRCA/Single_cell_map_anti-PD1/patient_clinical.txt', sep='\t')
patient_clinical_df

,ID,E_NE,Age_category,Histological_type,Type,Time_between_biopsy_and_surgery,pTNM,cTNM,sTILs_core,sTILs_resection,Ki67_core,Ki67_resection,Pre_post_menopausal
0,1,ND,41-50,IBC-NST,ER-/PR-/HER2+,11,pT1cN0,cT2N0,30,55,High,High,Pre
1,2,E,41-50,IBC-NST,TNBC,9,pT2N0,cT1N0,54,50,High,High,Pre
2,3,E,51-60,IBC-NST,TNBC,9,pT3N0,cT2mN0,86,92,High,High,Post
3,4,NE,81-90,IBC-NST,TNBC,9,pT1cN0,cT2N0,8,11,High,High,Post
4,5,NE,61-70,Carcinoma with apocrine differentiation,TNBC,8,pT2N1,cT2N0,1,6,Low,Low,Post
5,6,NE,71-80,IBC-NST,ER-/PR-/HER2+,9,pT2N0,cT2N0,8,15,Intermediate,Low,Post
6,7,NE,71-80,Metaplastic carcinoma,TNBC,11,pT3N0,cT3N0,0,7,High,High,Post
7,8,E,61-70,IBC-NST,ER-/PR-/HER2+,8,pT3N0,cT2N0,12,9,High,High,Post
8,9,NE,41-50,IBC-NST,ER+/PR+/HER2+,9,pT2N1,cT2N0,3.6,2,Intermediate,Intermediate,Pre
9,10,E,41-50,IBC-NST,TNBC,15,pT1cN0,cT1N0,1,37,High,High,Pre
10,11,NE,71-80,IBC-NST,TNBC,8,rpT2Nx,rcT2mN0,5,6,High,Low,Post
11,12,E,61-70,IBC-NST,ER+/PR+/HER2-,9,pT2N1,cT2N1,3.2,44,High,ND,Post
12,13,NE,41-50,IBC-NST,ER+/PR+/HER2-,8,pT2N1,cT2N0,2,1,Low,Intermediate,Pre
13,14,E,61-70,IBC-NST,ER+/PR+/HER2-,13,pT2N0,cT2N0,26,50,Intermediate,High,Post
14,15,ND,30-40,IBC-NST,TNBC,13,pT2N1,cT2N1,22,6,High,High,Pre
15,16,E,61-70,IBC-NST,TNBC,7,pT1cN0,cT1N0,7.5,12,High,High,Post
16,17,NE,51-60,IBC-NST,ER+/PR+/HER2-,8,pT2N1,cT2N1,5,3,Intermediate,High,Post
17,18,NE,51-60,IBC-NST,ER+/PR+/HER2-,8,pT1cN0,cT2N0,1.5,2,High,High,Post
18,19,NE,61-70,IBC-NST,TNBC,9,pT2N0,cT2N0,4,15,High,High,Post
19,20,NE,41-50,IBC-NST,ER+/PR+/HER2-,12,pT3N1,cT2N1,0,0,Low,Low,Pre
20,21,NE,51-60,IBC-NST,ER+/PR+/HER2-,14,pT2N0,cT2mN0,0,0,High,Intermediate,Post
21,22,NE,41-50,IBC-NST,ER+/PR+/HER2-,9,pT2N0,cT2N0,31,48,High,High,Pre
22,23,NE,41-50,IBC-NST,TNBC,12,pT1cN0(sn),cT1N0M0,ND,2.4,ND,High,Post
23,24,E,71-80,ILC-ST,ER+/PR+/HER2-,9,pT3N3a,cT3N1M0,1,7,Low,Low,Post
24,25,E,51-60,Carcinoma with apocrine differentiation,TNBC,7,pT1c(m)N0(sn),cT2mN0M0,65,68,High,High,Pre
25,26,NE,41-50,IBC-NST,ER+/PR+/HER2+,12,pT2N1mi(sn),cT2N0M0,0.2,15,High,Intermediate,Pre
26,27,NE,71-80,IBC-NST,TNBC,9,pT1cN0(sn),cT1N0M0,1.2,2,High,High,Post
27,28,NE,51-60,IBC-NST,ER+/PR+/HER2-,9,pT3(m)N1a,cT3N1M0,1,2,Low,Low,Post
28,29,NE,41-50,IBC-NST,ER+/PR-/HER2-,8,pT2N1a(sn),cT2N0M0,15,5,Intermediate,Intermediate,Pre
29,30,NE,61-70,IBC-NST,ER+/PR+/HER2-,7,pT2(m)N1a,cT2mN1M0,9,29,Low,Low,Post
30,31,NE,41-50,IBC-NST,ER+/PR+/HER2-,7,pT2N1a,cT2N1M0,0.4,9,Low,Low,Pre
31,32,E,30-40,IBC-NST with medullary pattern,TNBC,12,ypT1N0,ycT1N0,ND,ND,Intermediate,Intermediate,Pre
32,33,NE,51-60,IBC-NST,ER-/PR-/HER2+,12,ypT0N0,ycT2N1,No tumor,ND,ND,ND,Post
33,34,E,30-40,IBC-NST,TNBC,12,ypT2N0,ycT2N0,34,35,High,Intermediate,Pre
34,35,E,71-80,IBC-NST,TNBC,8,ypT1N2,ycT2N1,No tumor,ND,Low,ND,Post
35,36,NE,41-50,IBC-NST*,TNBC,9,ypT1N1,ycT1N0,15,6,High,High,Post
36,37,NE,61-70,IBC-NST,ER+/PR+/HER2-,7,ypT2N3,ycT2N0,1,2,ND,ND,Post
37,38,NE,51-60,IBC-NST,ER+/PR+/HER2-,9,ypT2N1,ycT1N0,No tumor,3,Low,Low,Pre
38,39,NE,51-60,IBC-NST,ER+/PR+/HER2-,9,ypT3N3,ycT2N1,2,1,High,Low,Post
39,40,NE,51-60,IBC-NST,TNBC,9,ypT1bN0(sn),ycT2(m)N0M0,8,ND,Low,Low,Post
40,41,NE,30-40,IBC-NST,TNBC,8,ypT2N1a,ycT2N1M0,1.2,0.2,High,High,Pre
41,42,NE,61-70,IBC-NST,ER+/PR+/HER2-,8,ypT2(m)N1a,ycT4bN0M0,0.4,0.4,Low,Low,Post

In [40]:
combined_ad.obs['new_id'] = [int(i.split('_')[-1]) for i in combined_ad.obs['patient_id']]

In [41]:
# Step 1: Reset index for merging, but save cell IDs
merged = combined_ad.obs.reset_index().merge(
    patient_clinical_df,
    left_on='new_id',
    right_on='ID',
    how='left'
)

# Step 2: Restore original index (cell barcodes)
merged = merged.set_index('index')

# Step 3: Assign back
combined_ad.obs = merged
combined_ad.obs

,nCount_RNA,nFeature_RNA,patient_id,timepoint,expansion,BC_type,cellType,cohort,new_id,ID,...,Histological_type,Type,Time_between_biopsy_and_surgery,pTNM,cTNM,sTILs_core,sTILs_resection,Ki67_core,Ki67_resection,Pre_post_menopausal
index,,,,,,,,,,,,,,,,,,,,,
BIOKEY_13_Pre_AAACGGGTCCGAACGC-1,742,424,BIOKEY_13,Pre,NaN,HER2+,Cancer_cell,treatment_naive,13,13,...,IBC-NST,ER+/PR+/HER2-,8,pT2N1,cT2N0,2,1,Low,Intermediate,Pre
BIOKEY_13_Pre_AACCATGAGGCAATTA-1,14902,4089,BIOKEY_13,Pre,NaN,HER2+,Cancer_cell,treatment_naive,13,13,...,IBC-NST,ER+/PR+/HER2-,8,pT2N1,cT2N0,2,1,Low,Intermediate,Pre
BIOKEY_13_Pre_AACTCCCCATCCGTGG-1,410,246,BIOKEY_13,Pre,NaN,HER2+,Cancer_cell,treatment_naive,13,13,...,IBC-NST,ER+/PR+/HER2-,8,pT2N1,cT2N0,2,1,Low,Intermediate,Pre
BIOKEY_13_Pre_AACTTTCTCCACGTGG-1,658,331,BIOKEY_13,Pre,NaN,HER2+,Cancer_cell,treatment_naive,13,13,...,IBC-NST,ER+/PR+/HER2-,8,pT2N1,cT2N0,2,1,Low,Intermediate,Pre
BIOKEY_13_Pre_AAGCCGCGTCGCATAT-1,1172,719,BIOKEY_13,Pre,NaN,HER2+,Cancer_cell,treatment_naive,13,13,...,IBC-NST,ER+/PR+/HER2-,8,pT2N1,cT2N0,2,1,Low,Intermediate,Pre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BIOKEY_42_On_TTCTTAGCAATTCCTT-1,12833,3484,BIOKEY_42,On,NE,ER+,Cancer_cell,neoadjuvant_chemo,42,42,...,IBC-NST,ER+/PR+/HER2-,8,ypT2(m)N1a,ycT4bN0M0,0.4,0.4,Low,Low,Post
BIOKEY_42_On_TTGTAGGGTGGTTTCA-1,2802,1387,BIOKEY_42,On,NE,ER+,Cancer_cell,neoadjuvant_chemo,42,42,...,IBC-NST,ER+/PR+/HER2-,8,ypT2(m)N1a,ycT4bN0M0,0.4,0.4,Low,Low,Post
BIOKEY_42_On_TTTGCGCAGTACGCGA-1,624,347,BIOKEY_42,On,NE,ER+,Cancer_cell,neoadjuvant_chemo,42,42,...,IBC-NST,ER+/PR+/HER2-,8,ypT2(m)N1a,ycT4bN0M0,0.4,0.4,Low,Low,Post
BIOKEY_42_On_TTTGGTTAGAGCAATT-1,15145,4468,BIOKEY_42,On,NE,ER+,Cancer_cell,neoadjuvant_chemo,42,42,...,IBC-NST,ER+/PR+/HER2-,8,ypT2(m)N1a,ycT4bN0M0,0.4,0.4,Low,Low,Post
BIOKEY_42_On_TTTGTCACAAAGCGGT-1,8375,3148,BIOKEY_42,On,NE,ER+,Cancer_cell,neoadjuvant_chemo,42,42,...,IBC-NST,ER+/PR+/HER2-,8,ypT2(m)N1a,ycT4bN0M0,0.4,0.4,Low,Low,Post

In [42]:
# add more clinical information

combined_ad.obs['Final_cancer_type'] = 'Breast Cancer'
combined_ad.obs['Final_histological_subtype'] = combined_ad.obs['Histological_type']
combined_ad.obs['Final_molecular_subtype'] = combined_ad.obs['Type']
combined_ad.obs['Final_tissue'] = 'Breast'
combined_ad.obs['Final_sample_id'] = combined_ad.obs['patient_id']
combined_ad.obs['Final_patient_age'] = combined_ad.obs['Age_category']
combined_ad.obs['Final_patient_stage'] = combined_ad.obs['pTNM']
combined_ad.obs['Final_patient_treatment'] = combined_ad.obs['cohort']

In [43]:
combined_ad.obs['Project_ID'] = 'Single_cell_map_anti-PD1'
combined_ad.obs['Primary_or_Metastatic'] = 'Primary'

In [46]:
combined_ad.write_h5ad('../../Data/Cancer_cell_data_reprocessed/Single_cell_map_anti-PD1.BRCA.h5ad', compression='gzip')

In [47]:
combined_ad.raw.shape

(60517, 22567)

## Combined Single-Cell and Spatial Transcriptomics Reveal the Metabolic Evolvement of Breast Cancer during Early Dissemination

Paper: https://advanced.onlinelibrary.wiley.com/doi/10.1002/advs.202205395

Data downloaded from: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE225600

Link: 
- Matrix: https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE225600&format=file&file=GSE225600%5Fsc%5Fmatrix%2Emtx%2Egz
- Annotation: https://advanced.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fadvs.202205395&file=advs5030-sup-0003-DatasetS2.xlsx
- Patient clinical: https://advanced.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fadvs.202205395&file=advs5030-sup-0002-DatasetS1.xlsx

In [11]:
# Set the project directory
project_dir = "../../Data/BRCA/GSE225600/"  # <- change this for each project

# Load and preprocess
ad = load_and_preprocess_project(project_dir, 
                                 metadata_idx_key='Barcode', 
                                 Project_ID='GSE225600',
                                 Primary_or_Metastatic='Metastatic',
                                 further_pre=False)
ad

../../Data/BRCA/GSE225600/GSE225600_sc_matrix.mtx
../../Data/BRCA/GSE225600/GSE225600_sc_barcodes.tsv
../../Data/BRCA/GSE225600/GSE225600_sc_features.tsv
../../Data/BRCA/GSE225600/metadta.tsv
Loading: ../../Data/BRCA/GSE225600/GSE225600_sc_matrix.mtx

                         0
0      AAACCCAAGACGGTTG-L2
1      AAACCCAAGTCACTAC-L2
2      AAACCCAGTATTGAGA-L2
3      AAACCCATCAGCTAGT-L2
4      AAACCCATCTACCAGA-L2
...                    ...
81678  TTTGTTGTCCATCCGT-T7
81679  TTTGTTGTCCGTGTAA-T7
81680  TTTGTTGTCGTGCACG-T7
81681  TTTGTTGTCTCTGCCA-T7
81682  TTTGTTGTCTGGGATT-T7

[81683 rows x 1 columns]

                 0
0      MIR1302-2HG
1          FAM138A
2            OR4F5
3       AL627309.1
4       AL627309.3
...            ...
36596   AC141272.1
36597   AC023491.2
36598   AC007325.1
36599   AC007325.4
36600   AC007325.2

[36601 rows x 1 columns]

,MIR1302-2HG,FAM138A,OR4F5,AL627309.1,AL627309.3,AL627309.2,AL627309.5,AL627309.4,AP006222.2,AL732372.1,...,AC133551.1,AC136612.1,AC136616.1,AC136616.3,AC136616.2,AC141272.1,AC023491.2,AC007325.1,AC007325.4,AC007325.2
AAACCCAAGACGGTTG-L2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCCAAGTCACTAC-L2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCCAGTATTGAGA-L2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCCATCAGCTAGT-L2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACCCATCTACCAGA-L2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTTGTCCATCCGT-T7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGTCCGTGTAA-T7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGTCGTGCACG-T7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGTCTCTGCCA-T7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTTGTTGTCTGGGATT-T7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Running doublet detection on 81683 cells...

/home/wang3712/.local/lib/python3.8/site-packages/anndata/_core/anndata.py:1840: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wang3712/.local/lib/python3.8/site-packages/anndata/_core/anndata.py:1840: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wang3712/.local/lib/python3.8/site-packages/anndata/_core/anndata.py:1840: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wang3712/.local/lib/python3.8/site-packages/scanpy/preprocessing/_normalization.py:170: UserWarning: Received a view of an AnnData. Making a copy.
  view_to_actual(adata)

Automatically set threshold at doublet score = 0.69
Detected doublet rate = 0.0%
Estimated detectable doublet fraction = 3.4%
Overall doublet rate:
	Expected   = 6.0%
	Estimated  = 0.6%
  Detected 17 doublets (0.0%)

/home/wang3712/.local/lib/python3.8/site-packages/anndata/_core/anndata.py:1840: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

  After doublet removal: 81666 cells
Finished processing GSE225600. Shape: (62076, 36601)

/home/wang3712/.local/lib/python3.8/site-packages/anndata/_core/anndata.py:1840: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/wang3712/.local/lib/python3.8/site-packages/anndata/_core/anndata.py:1840: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 62076 × 36601
    obs: 'Barcode', 'sampleid', 'celltype', 'clusters', 'group', 'doublet_score', 'predicted_doublet', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'Project_ID', 'Primary_or_Metastatic'
    var: 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'scrublet'

In [23]:
meta_df = pd.read_csv('../../Data/BRCA/GSE225600/metadta.tsv', sep='\t')
# Remove "-1" (or any dash-number) from Barcode first
meta_df['Barcode_clean'] = meta_df['Barcode'].str.replace(r'-\d+$', '', regex=True)

# Then concatenate with sampleid
meta_df['new_name'] = meta_df['Barcode_clean'] + '-' + meta_df['sampleid']

meta_df = meta_df.set_index('new_name')
meta_df

,Barcode,sampleid,celltype,clusters,group,Barcode_clean
new_name,,,,,,
AAACCCAAGACGGTTG-L2,AAACCCAAGACGGTTG-1,L2,Endothelial cell,10,L,AAACCCAAGACGGTTG
AAACCCAAGTCACTAC-L2,AAACCCAAGTCACTAC-1,L2,Fibroblast,7,L,AAACCCAAGTCACTAC
AAACCCAGTATTGAGA-L2,AAACCCAGTATTGAGA-1,L2,T/NK cell,1,L,AAACCCAGTATTGAGA
AAACCCATCAGCTAGT-L2,AAACCCATCAGCTAGT-1,L2,T/NK cell,5,L,AAACCCATCAGCTAGT
AAACCCATCTACCAGA-L2,AAACCCATCTACCAGA-1,L2,B cell,3,L,AAACCCATCTACCAGA
...,...,...,...,...,...,...
TTTGTTGTCCATCCGT-T7,TTTGTTGTCCATCCGT-8,T7,T/NK cell,4,T,TTTGTTGTCCATCCGT
TTTGTTGTCCGTGTAA-T7,TTTGTTGTCCGTGTAA-8,T7,Epithelial cell,11,T,TTTGTTGTCCGTGTAA
TTTGTTGTCGTGCACG-T7,TTTGTTGTCGTGCACG-8,T7,T/NK cell,6,T,TTTGTTGTCGTGCACG
TTTGTTGTCTCTGCCA-T7,TTTGTTGTCTCTGCCA-8,T7,Fibroblast,14,T,TTTGTTGTCTCTGCCA
TTTGTTGTCTGGGATT-T7,TTTGTTGTCTGGGATT-8,T7,T/NK cell,4,T,TTTGTTGTCTGGGATT

In [24]:
shared_cells = list(set(ad.to_df().index).intersection(set(meta_df.index)))
shared_cells.sort()
len(shared_cells)

4109

In [25]:
ad = ad[shared_cells]
ad.obs = meta_df.loc[ad.to_df().index]
ad.obs

,Barcode,sampleid,celltype,clusters,group,Barcode_clean
AAACCCAAGGGTATAT-T7,AAACCCAAGGGTATAT-8,T7,Epithelial cell,12,T,AAACCCAAGGGTATAT
AAACCCACACATGTTG-T7,AAACCCACACATGTTG-8,T7,Epithelial cell,12,T,AAACCCACACATGTTG
AAACCCACACGACCTG-T2,AAACCCACACGACCTG-5,T2,Epithelial cell,11,T,AAACCCACACGACCTG
AAACCCACACTTGGCG-T7,AAACCCACACTTGGCG-8,T7,Epithelial cell,13,T,AAACCCACACTTGGCG
AAACCCAGTGGCGCTT-T7,AAACCCAGTGGCGCTT-8,T7,Epithelial cell,13,T,AAACCCAGTGGCGCTT
...,...,...,...,...,...,...
TTTGGTTGTGTAGTGG-T2,TTTGGTTGTGTAGTGG-5,T2,Epithelial cell,11,T,TTTGGTTGTGTAGTGG
TTTGTTGAGCGTTGTT-T2,TTTGTTGAGCGTTGTT-5,T2,Epithelial cell,12,T,TTTGTTGAGCGTTGTT
TTTGTTGCATGTGCTA-T3,TTTGTTGCATGTGCTA-6,T3,Epithelial cell,13,T,TTTGTTGCATGTGCTA
TTTGTTGTCCGTGTAA-T7,TTTGTTGTCCGTGTAA-8,T7,Epithelial cell,11,T,TTTGTTGTCCGTGTAA
TTTGTTGTCTTGAACG-T2,TTTGTTGTCTTGAACG-5,T2,Epithelial cell,11,T,TTTGTTGTCTTGAACG

In [28]:
from collections import Counter

counts = Counter(ad.var_names)
duplicates = [k for k, v in counts.items() if v > 1]
print("Duplicated gene names:", duplicates)

Duplicated gene names: []

In [29]:
ad.var_names_make_unique()
ad

AnnData object with n_obs × n_vars = 4109 × 36601
    obs: 'Barcode', 'sampleid', 'celltype', 'clusters', 'group', 'Barcode_clean'
    var: 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'scrublet', 'pca', 'neighbors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [31]:
ad.raw = ad.copy()
ad.raw.shape

(4109, 36601)

In [33]:
ad = filter_and_recompute(adata=ad, 
                          celltype_col='celltype', 
                          celltypes_to_keep=['Epithelial cell'],
                          further_pre=True)
ad

Original shape: (4109, 36601)
Filtered shape: (4109, 36601)
Recalculated PCA and UMAP.

AnnData object with n_obs × n_vars = 4109 × 36601
    obs: 'Barcode', 'sampleid', 'celltype', 'clusters', 'group', 'Barcode_clean'
    var: 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'scrublet', 'pca', 'neighbors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [37]:
patient_clinical_df = pd.read_csv('../../Data/BRCA/GSE225600/patient_clinical.txt', sep='\t')
patient_clinical_df

,Patient ID,Age (year),Sex,Tumor size (cm),Lymph nodes,Cancer type,Grade,ER,PR,HER2,Ki-67,Stage (AJCC 8),Preoperative treatments
0,1,36,Female,2.2*2*1.8,1/15,IDC,III,60%,>80%,3+,60%,IIB,No
1,2,47,Female,3.2*2*2.5,2/20,IDC,III,0,0,3+,30%,IIB,No
2,3,46,Female,4.5*5*3,5/20,IDC,III,>80%,>80%,3+,20%,IIIA,No
3,4,62,Female,3*2.8*2.5,1/20,IDC,III,>80%,>80%,1+,40%,IIB,No

In [38]:
# add more clinical information
ad.obs['Project_ID'] = 'GSE225600'
ad.obs['Primary_or_Metastatic'] = 'Metastatic'
ad.obs['Final_cancer_type'] = 'Breast Cancer'
ad.obs['Final_histological_subtype'] = 'Invasive ductal carcinoma'
ad.obs['Final_molecular_subtype'] = 'Unknown'
ad.obs['Final_tissue'] = 'Breast'
ad.obs['Final_sample_id'] = ad.obs['sampleid']
ad.obs['Final_patient_age'] = 'Unknown'
ad.obs['Final_patient_stage'] = 'Unknown'
ad.obs['Final_patient_treatment'] = 'Naive'

In [40]:
ad.write_h5ad('../../Data/Cancer_cell_data_reprocessed/GSE225600.BRCA.h5ad', compression='gzip')

In [42]:
ad

AnnData object with n_obs × n_vars = 4109 × 36601
    obs: 'Barcode', 'sampleid', 'celltype', 'clusters', 'group', 'Barcode_clean', 'Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 'Final_molecular_subtype', 'Final_tissue', 'Final_sample_id', 'Final_patient_age', 'Final_patient_stage', 'Final_patient_treatment'
    var: 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'scrublet', 'pca', 'neighbors', 'umap', 'sampleid_colors', 'group_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

## Integrate the data

In [ ]:
data_dir = '../../Data/Cancer_cell_data_reprocessed/'
all_h5_files = os.listdir(data_dir)
all_h5_files.sort()

all_h5_files

In [ ]:
cancer_ad_list = []
for h5 in all_h5_files:
    if h5.__contains__('ntegrated'):
        continue
    if not h5.__contains__('BRCA'):
        continue
    print(h5)
    # continue
    tmp_ad = sc.read_h5ad(data_dir+h5)
    if h5.__contains__('2102-Breastcancer'):
        tmp_ad.obs_names = tmp_ad.obs['Cell']
    # break
    
    if tmp_ad.var_names[0].startswith('ENSG'):
        tmp_ad.var_names = tmp_ad.var.feature_name
        tmp_ad.raw.var.index = tmp_ad.var.feature_name
        # tmp_ad.raw.var_names = tmp_ad.var.feature_name
    cancer_ad_list.append(tmp_ad)
    tmp_ad.X = tmp_ad.raw.X.copy()
    print(cancer_ad_list[-1])
    display(tmp_ad.to_df())

In [ ]:
for ad in cancer_ad_list:
    # print(ad)
    print(ad.shape)
    print(ad.raw.shape)

for i, ad in enumerate(cancer_ad_list):
    if ad.raw is not None:
        if not ad.raw.var_names.is_unique:
            print(f"AnnData {i} has duplicate raw.var_names!")
            print(ad.obs['Project_ID'])

In [ ]:
memory_usgae()

In [ ]:
combined_ad = ann.concat(cancer_ad_list, join="inner", axis=0)
combined_ad

In [ ]:
combined_ad.raw.shape

In [ ]:
combined_ad = reprocess_all(combined_ad)

In [ ]:
combined_ad

In [ ]:
combined_ad.obs["Final_histological_subtype"].value_counts()

In [ ]:
combined_ad.obs["Final_histological_subtype_backup"] = combined_ad.obs["Final_histological_subtype"].copy()

In [ ]:
def unify_histological_subtype(subtype):
    subtype = str(subtype).lower()
    if "ductal" in subtype and "lobular" in subtype:
        return "BRCA: Mixed ductal/lobular carcinoma"
    elif 'ibc' in subtype:
        return 'BRCA: Invasive breast carcinoma'
    elif "invasive ductal" in subtype or "innvasive ductal" in subtype:
        return "BRCA: Invasive ductal carcinoma"
    elif "lobular" in subtype or 'ilc' in subtype:
        return "BRCA: Invasive lobular carcinoma"
    elif "mucinous" in subtype:
        return "BRCA: Invasive mucinous carcinoma"
    elif "metaplastic" in subtype:
        return "BRCA: Metaplastic carcinoma"
    elif "apocrine" in subtype:
        return "BRCA: Invasive apocrine carcinoma"
    elif "malignant neoplasm" in subtype:
        return "BRCA: Malignant neoplasm (unspecified)"
    elif "breast carcinoma" in subtype:
        return "BRCA: Breast carcinoma (unspecified)"
    elif "metastatic" in subtype:
        return "BRCA: Metastatic carcinoma"
    elif subtype == "n/a" or subtype.strip() in {"", "nan"}:
        return "BRCA: Unspecified"
    else:
        return subtype.strip().capitalize()

combined_ad.obs["Final_histological_subtype"] = combined_ad.obs["Final_histological_subtype_backup"].apply(unify_histological_subtype)
combined_ad.obs['Final_histological_subtype'].value_counts()

In [ ]:
combined_ad.obs['Final_molecular_subtype'].value_counts()

In [ ]:
combined_ad.obs["Final_molecular_subtype_backup"] = combined_ad.obs["Final_molecular_subtype"].copy()

In [ ]:
# Define mapping dictionary
def unify_molecular_subtype(val):
    val = str(val).strip().lower()
    if val in {"tnbc", "triple negative", "er-/pr-/her2-"}:
        return "BRCA: Triple Negative"
    elif val in {"her2", "her2+", "her2 positive"}:
        return "BRCA: HER2+"
    elif val in {"er+/pr+/her2-", "luminal a-like"}:
        return "BRCA: ER+/PR+/HER2-"
    elif val in {"luminal b-like", "luminal-her2+", "er+/pr+/her2+", "her2+/er+"}:
        return "BRCA: ER+/PR+/HER2+"
    elif val == "er+/pr+/":
        return "BRCA: ER+"
    elif val == "er+":
        return "BRCA: ER+"
    elif val == "er+/pr-/her2-":
        return "BRCA: ER+"
    elif val == "er-/pr-/her2+":
        return "BRCA: HER2+"
    elif val == "nan" or val in {"", "none"}:
        return "BRCA: Unspecified"
    elif val == "unknown":
        return "BRCA: Unspecified"
    else:
        return val.capitalize()

# Apply mapping
combined_ad.obs['Final_molecular_subtype'] = combined_ad.obs['Final_molecular_subtype_backup'].apply(unify_molecular_subtype)

# Optional: check new values
print(combined_ad.obs['Final_molecular_subtype'].value_counts())

In [ ]:
combined_ad.obs['Final_tissue'] .value_counts()

In [ ]:
combined_ad.obs['Final_tissue'] = combined_ad.obs['Final_tissue'].astype(str).str.capitalize()

In [ ]:
combined_ad.obs['Final_tissue'] .value_counts()

In [ ]:
combined_ad.obs["Final_patient_age_backup"] = combined_ad.obs["Final_patient_age"]

In [ ]:

def clean_patient_age(age):
    if pd.isna(age):
        return np.nan
    age = str(age).strip()
    if age.lower() == "unknown":
        return np.nan
    elif "-" in age:
        # Convert age ranges like '46-50' to their midpoint
        parts = age.split("-")
        try:
            return int((int(parts[0]) + int(parts[1])) / 2)
        except:
            return np.nan
    else:
        try:
            return int(age)
        except:
            return np.nan

# Apply cleaning
combined_ad.obs["Final_patient_age"] = combined_ad.obs["Final_patient_age_backup"].apply(clean_patient_age)

In [ ]:
combined_ad

In [ ]:
for obs in ['Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 
            'Final_molecular_subtype', 'Final_tissue', 'Final_patient_age', 'Final_patient_stage', 'Final_patient_treatment']:
    sc.pl.umap(combined_ad, color=obs)

### Harmony integration

In [ ]:
combined_ad

In [ ]:
Z = harmonize(combined_ad.obsm['X_pca'], combined_ad.obs, batch_key = ['Project_ID'])

In [ ]:
combined_ad.obsm['X_pca_harmony'] = Z

In [ ]:
sc.pp.neighbors(combined_ad, n_neighbors=15, use_rep='X_pca_harmony')
sc.tl.umap(combined_ad)

In [ ]:
for obs in ['Project_ID', 'Primary_or_Metastatic', 'Final_cancer_type', 'Final_histological_subtype', 
            'Final_molecular_subtype', 'Final_tissue', 'Final_patient_age', 'Final_patient_stage', 'Final_patient_treatment']:
    sc.pl.umap(combined_ad, color=obs)

In [ ]:
combined_ad.obs['Final_patient_age_backup'] = combined_ad.obs['Final_patient_age_backup'].astype(str)

In [ ]:

combined_ad.write_h5ad('../../Data/Cancer_cell_data_reprocessed/BRCA_integrated.harmony.h5ad', compression='gzip')